/******************************************************************************
 * @file        aot_conv_2.c
 * @brief       Autogenerated AOT CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #2 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_conv_2.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 0
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 32
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2_input_dims = { .n = 1, .h = 48, .w = 48, .c = 8 };

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2_filter_dims = { .n =  16, .h = 1, .w = 1, .c = 8 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 16 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2_output_dims = { .n = 1, .h = 48, .w = 48, .c = 16 };

// Quantization parameters (per-channel quantization)
static const int32_t conv_2_multiplier[16] = {
  1740558848, 1549241216, 2047988864, 2067897344, 1571691520, 1340550912, 1424193536, 1829389312, 2072712576, 1218009472, 1496189440, 1430332032, 1762944768, 1272555776, 1403573376, 1663644928
};
static const int32_t conv_2_shift[16] = {
  -6, -6, -7, -8, -8, -7, -6, -6, -8, -7, -7, -7, -6, -7, -6, -6
};

// Offsets and activation parameters.
static const int32_t conv_2_input_zero_point = -128;
static const int32_t conv_2_output_zero_point = -128;

// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t conv_2_weights[] = {
  127, -22, 60, -39, 86, 2, 18, -3, -6, 30, -68, -127, 71, -72, 125, -44, 92, 127, -7, -21, 
  -51, -2, 56, -1, 17, -54, 98, 52, 127, 16, -28, -99, -31, 34, 96, -7, 70, -3, 116, -127, 
  -11, 12, 15, 39, 30, 127, -7, 13, -5, 6, -16, 127, 42, -7, 31, 6, -7, -7, 32, -127, 
  -17, 16, -18, 24, 0, -46, -77, 22, 41, -8, -23, -127, -29, 127, 13, 25, 64, 29, 101, -16, 
  22, -20, -25, -41, -14, -127, -9, -27, -127, -32, -11, -9, -11, -17, 97, -38, 29, -25, 33, 127, 
  -26, -54, 51, 75, -32, 35, 127, 17, 16, 72, 35, 44, -111, -60, 87, 36, -101, -40, -127, -71, 
  -10, 21, -13, -34, -46, -15, 127, -11
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t conv_2_bias[] = {
  -1832, 2518, -909, 3142, 5726, 493, -2770, 3802, 8393, -144, 7745, 3927, -3660, -221, 5163, -327
};
#else
static NS_PUT_IN_TCM int32_t *conv_2_bias = NULL;
#endif


alignas(16) static NS_PUT_IN_TCM int8_t conv_2_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context conv_2_context = {
    .buf = conv_2_scratch_buffer,
    .size = sizeof(conv_2_scratch_buffer),
};

const cmsis_nn_per_channel_quant_params conv_2_quant_params = {
    .multiplier = (int32_t*)conv_2_multiplier,
    .shift = (int32_t*)conv_2_shift,
};


const cmsis_nn_conv_params conv_2_conv_params = {
    .input_offset = -conv_2_input_zero_point,
    .output_offset = conv_2_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_conv_2_init(void)
{
    return 0;
}

int32_t aot_conv_2_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_convolve_wrapper_s8(
        &conv_2_context,
        &conv_2_conv_params,
        &conv_2_quant_params,
        &conv_2_input_dims,
        input,
        &conv_2_filter_dims,
        conv_2_weights,
        &conv_2_bias_dims,
        conv_2_bias,
        &conv_2_output_dims,
        output
    );

}
