/******************************************************************************
 * @file        aot_depthwise_conv_3.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #3 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_3.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_3_input_dims = { .n = 1, .h = 48, .w = 48, .c = 16 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_3_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 16 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_3_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 16 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_3_output_dims = { .n = 1, .h = 24, .w = 24, .c = 16 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_3_multiplier[16] = {
  1708841872, 2035120732, 1755327149, 1102250035, 2061352956, 1700200755, 1181457292, 1515078530, 1342733388, 1946705614, 1290012645, 1133273217, 1868352483, 2041886983, 1951811605, 1209859860
};
static const int32_t dw_3_shift[16] = {
  -8, -8, -7, -6, -6, -6, -7, -7, -6, -7, -5, -6, -8, -7, -8, -7
};

// Offsets and activation parameters.
static const int32_t dw_3_input_zero_point = -128;
static const int32_t dw_3_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_3_weights[] = {
  -10, 19, 1, -29, -127, -127, -18, -63, -33, -31, -46, -29, 12, 23, -45, -124, -23, 10, -1, 127, 
  -58, 36, 48, -89, -110, 13, 127, -33, 38, 27, -120, -84, 19, -59, -3, 92, 9, 19, 38, -59, 
  116, 33, -64, -13, 27, -3, -57, -5, 50, -72, -14, 14, -76, 81, 90, -80, -86, 43, 5, -48, 
  117, 113, -52, -127, 63, -108, -127, 66, -12, -110, 113, -127, -45, 127, -61, -127, 127, 127, -127, -23, 
  6, -43, -70, 59, 18, 30, 22, -58, 94, 100, 71, -38, 59, 27, -97, 26, 104, -66, 19, 0, 
  21, 64, 127, -4, -118, 69, 14, -39, 121, 84, -35, -39, 127, -127, -66, -83, 18, 21, 98, -40, 
  127, 114, -48, -66, 98, 94, -87, 7, 19, 9, -53, -30, 21, -53, 21, -12, 70, 20, 14, -49, 
  3, 20, -83, 53
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_3_bias[] = {
  -1678, 11463, 10067, 182, 7018, 703, 417, 11033, 3731, -6483, -303, 13894, -6733, -3723, 10421, 11383
};
#else
static NS_PUT_IN_TCM int32_t *dw_3_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_3_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context dw_3_context = {
    .buf = dw_3_scratch_buffer,
    .size = sizeof(dw_3_scratch_buffer),
};


int32_t aot_depthwise_conv_3_init(void)
{
    return 0;
}

const cmsis_nn_per_channel_quant_params dw_3_quant_params = {
    .multiplier = (int32_t*)dw_3_multiplier,
    .shift = (int32_t*)dw_3_shift,
};

const cmsis_nn_dw_conv_params dw_3_dw_conv_params = {
    .input_offset = -dw_3_input_zero_point,
    .output_offset = dw_3_output_zero_point,
    .ch_mult = 1,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_3_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_3_context,
        &dw_3_dw_conv_params,
        &dw_3_quant_params,
        &dw_3_input_dims,
        input,
        &dw_3_filter_dims,
        dw_3_weights,
        &dw_3_bias_dims,
        dw_3_bias,
        &dw_3_output_dims,
        output
    );

}
