/******************************************************************************
 * @file        aot_strided_slice_2.c
 * @brief       Autogenerated AOT STRIDED_SLICE kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-03.
 *   This kernel represents node #2 in the corresponding graph.
 *
 * @date        2025-06-03
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_strided_slice_2.h"

// Input dimensions: input shape is [B_IN, H_IN, W_IN, C_IN]
static const cmsis_nn_dims strided_slice_2_input_dims = { .n = 1, .h = 8, .w = 8, .c = 3 };

// Begin dimensions: begin shape is [B_BEGIN, H_BEGIN, W_BEGIN, C_BEGIN]
static const cmsis_nn_dims strided_slice_2_begin_dims = { .n = 0, .h = 2, .w = 3, .c = 0 };

// Stride dimensions: stride shape is [B_STRIDE, H_STRIDE, W_STRIDE, C_STRIDE]
static const cmsis_nn_dims strided_slice_2_stride_dims = { .n = 1, .h = 1, .w = 1, .c = 1 };

// Output dimensions: output shape is [B_OUT, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims strided_slice_2_output_dims = { .n = 1, .h = 4, .w = 4, .c = 3 };


int32_t
aot_strided_slice_2_init(void)
{
    return 0;
}

int32_t
aot_strided_slice_2_run(const int8_t* __restrict input, int8_t* __restrict output)
{
    return arm_strided_slice_s8(
        input,
        output,
        &strided_slice_2_input_dims,
        &strided_slice_2_begin_dims,
        &strided_slice_2_stride_dims,
        &strided_slice_2_output_dims
    );

}
