/******************************************************************************
 * @file        aot_conv_4.c
 * @brief       Autogenerated AOT CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #4 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_conv_4.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 0
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 64
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_4_input_dims = { .n = 1, .h = 24, .w = 24, .c = 16 };

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_4_filter_dims = { .n =  32, .h = 1, .w = 1, .c = 16 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_4_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 32 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_4_output_dims = { .n = 1, .h = 24, .w = 24, .c = 32 };

// Quantization parameters (per-channel quantization)
static const int32_t conv_4_multiplier[32] = {
  1767411712, 1763559680, 1525844096, 1494493824, 1813769472, 1173590272, 2123988224, 1502771072, 1213741696, 1415458176, 1261352960, 1388146048, 1295061888, 1245209600, 1942248192, 1740164608, 1105266304, 1229387904, 1567480960, 2096859136, 
  1771123072, 1273897216, 1236698752, 1111124864, 1143862528, 2139635584, 2050267776, 1243261568, 1469351424, 2043273728, 1991967232, 1221293184
};
static const int32_t conv_4_shift[32] = {
  -8, -9, -7, -7, -8, -8, -8, -7, -7, -7, -7, -7, -6, -7, -7, -8, -7, -8, -7, -8, 
  -8, -7, -8, -7, -6, -9, -8, -8, -7, -7, -7, -7
};

// Offsets and activation parameters.
static const int32_t conv_4_input_zero_point = -128;
static const int32_t conv_4_output_zero_point = -128;

// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t conv_4_weights[] = {
  -46, -67, 63, 102, 30, 46, 50, 115, 13, -127, 33, -25, 34, 22, 7, -37, -41, 8, 17, -116, 
  -19, -21, 13, 53, 127, 13, -14, 35, -27, -72, 45, -5, -110, 8, 106, -29, 28, 25, 76, -23, 
  68, -127, 43, 7, 22, -36, 3, 67, -5, -16, -9, -33, 63, 127, -20, 24, 9, -35, 109, 76, 
  6, -3, 45, 16, 62, -40, -127, -16, -12, 38, -27, -50, 48, 86, 15, 118, 40, -32, 20, -82, 
  -7, 3, -100, 84, -25, -31, 55, -59, 5, 25, 4, 127, -63, 6, -4, 58, 10, 27, 21, -52, 
  -45, -1, 24, -111, 23, -28, 6, 44, -18, 127, -9, 46, 66, -78, -12, -8, 127, 34, 25, 38, 
  72, 52, 12, -8, -9, 80, -43, -29, -23, 12, -51, 92, -13, -62, -127, 103, -47, -18, -36, -25, 
  12, 4, -54, 9, -8, -73, 19, 67, -15, 13, 127, -92, 2, -2, 33, 24, 7, -69, -18, 10, 
  34, -30, 10, -63, -12, 37, 42, 16, -16, 1, 11, 56, -55, 127, 33, -44, -22, -44, 9, 47, 
  -21, 25, -14, -41, 127, -83, 20, 13, 34, 41, -14, -26, -71, 50, 86, 15, -11, 19, 16, -43, 
  28, -21, 6, 127, -32, -31, -34, 52, 33, -39, -30, 127, 47, 57, -12, -52, 27, 43, 51, -7, 
  43, -4, -71, -22, -3, 16, 52, -127, -10, 8, 13, 35, 36, 52, 10, 32, -29, -8, 2, 43, 
  -16, -46, -54, -63, 105, -75, -38, -127, 21, 119, -37, 121, 11, -16, -81, 39, 2, -14, 100, 7, 
  30, 12, 25, 6, 6, -127, 11, 105, -7, 25, -91, 20, 101, -7, -11, 127, -79, -42, 17, 111, 
  -21, 8, -22, 37, -107, 65, 23, 40, 87, 54, 25, -20, 127, -9, 21, 53, -24, 35, -5, 21, 
  -18, 80, -54, -88, 65, -10, 24, -11, 127, 16, -6, -25, 106, 48, 8, 45, 34, -102, -3, -96, 
  7, -5, 2, -2, 1, 9, -59, -13, 127, 14, -6, 2, 32, 23, -12, 11, 30, -33, -19, -4, 
  42, 47, -59, 25, -30, -16, 55, -43, 127, 4, 53, -25, 13, 11, -8, 24, 106, -8, -44, -49, 
  -17, -20, -12, 125, 14, -59, -38, 127, -3, -28, -126, -69, -22, 6, -9, -10, -3, 127, 6, 43, 
  -43, -49, -19, -33, -50, -25, 41, -6, 1, 30, 43, -14, 11, -12, 4, 31, -78, 127, 0, -38, 
  23, -1, -81, -9, 42, 4, 7, -11, 8, -50, -7, 127, -27, 13, 0, 48, 98, 14, -12, 76, 
  -20, 30, 74, 101, 71, -39, 5, 24, 0, 127, 54, 121, 76, -95, -39, -14, -98, 69, 5, 127, 
  -28, 114, 68, 40, -12, -58, 63, -12, -35, -3, -49, -23, 12, 4, 79, 18, 63, -22, 1, -8, 
  127, 12, 43, 15, 47, 36, 31, 69, 32, -7, 40, -2, -19, -127, -7, 16, -6, 58, -90, -25, 
  1, 10, 3, 5, -2, 127, -18, 15, -17, 0, 109, -2, -12, -6, 12, -5, -56, -7, 65, 27, 
  -32, 12, 15, 55, -43, 73, 25, -66, 115, 110, 67, -127
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t conv_4_bias[] = {
  -2541, 14950, -4824, -4847, 5154, 3978, -693, -9367, 10924, 1481, -2643, -130, -9312, -269, -2186, 3525, -6653, -966, -6803, -1263, 
  3494, 6204, 350, 5658, -6192, 5517, -22586, 8517, -2158, -4145, 446, -6711
};
#else
static NS_PUT_IN_TCM int32_t *conv_4_bias = NULL;
#endif


alignas(16) static NS_PUT_IN_TCM int8_t conv_4_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context conv_4_context = {
    .buf = conv_4_scratch_buffer,
    .size = sizeof(conv_4_scratch_buffer),
};

const cmsis_nn_per_channel_quant_params conv_4_quant_params = {
    .multiplier = (int32_t*)conv_4_multiplier,
    .shift = (int32_t*)conv_4_shift,
};


const cmsis_nn_conv_params conv_4_conv_params = {
    .input_offset = -conv_4_input_zero_point,
    .output_offset = conv_4_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_conv_4_init(void)
{
    return 0;
}

int32_t aot_conv_4_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_convolve_wrapper_s8(
        &conv_4_context,
        &conv_4_conv_params,
        &conv_4_quant_params,
        &conv_4_input_dims,
        input,
        &conv_4_filter_dims,
        conv_4_weights,
        &conv_4_bias_dims,
        conv_4_bias,
        &conv_4_output_dims,
        output
    );

}
