/******************************************************************************
 * @file        aot_model.c
 * @brief       Autogenerated AOT model
 * @details     This model was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   Subgraph: main.
 *   Model Description: MLIR Converted.
 * @version     v1.0.0
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include <stdint.h>
#include <math.h>
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "ns_ambiqsuite_harness.h"
#include "aot_resource_variables.h"
#include "aot_model.h"
#include "aot_conv_0.h"
#include "aot_depthwise_conv_1.h"
#include "aot_conv_2.h"
#include "aot_depthwise_conv_3.h"
#include "aot_conv_4.h"
#include "aot_depthwise_conv_5.h"
#include "aot_conv_6.h"
#include "aot_depthwise_conv_7.h"
#include "aot_conv_8.h"
#include "aot_average_pool_9.h"
#include "aot_fully_connected_11.h"
#include "aot_softmax_12.h"

const int32_t aot_inputs_len[1] = {
    490
};

const int32_t aot_inputs_zero_point[1] = {
    83
};

const float aot_inputs_scale[1] = {
    0.5847029089927673
};

const int32_t aot_outputs_len[1] = {
    12
};

const int32_t aot_outputs_zero_point[1] = {
    -128
};

const float aot_outputs_scale[1] = {
    0.00390625
};


alignas(16) static int8_t model_buffer[16000];


int32_t aot_model_init(aot_model_context_t *context)
{

    int32_t status = 0;

    // Initializing operator 0 (conv_0)
    if (context->callback) {
        context->callback(0, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_0_init();
    if (context->callback) {
        context->callback(0, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 1 (depthwise_conv_1)
    if (context->callback) {
        context->callback(1, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_1_init();
    if (context->callback) {
        context->callback(1, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 2 (conv_2)
    if (context->callback) {
        context->callback(2, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_2_init();
    if (context->callback) {
        context->callback(2, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 3 (depthwise_conv_3)
    if (context->callback) {
        context->callback(3, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_3_init();
    if (context->callback) {
        context->callback(3, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 4 (conv_4)
    if (context->callback) {
        context->callback(4, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_4_init();
    if (context->callback) {
        context->callback(4, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 5 (depthwise_conv_5)
    if (context->callback) {
        context->callback(5, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_5_init();
    if (context->callback) {
        context->callback(5, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 6 (conv_6)
    if (context->callback) {
        context->callback(6, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_6_init();
    if (context->callback) {
        context->callback(6, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 7 (depthwise_conv_7)
    if (context->callback) {
        context->callback(7, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_7_init();
    if (context->callback) {
        context->callback(7, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 8 (conv_8)
    if (context->callback) {
        context->callback(8, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_8_init();
    if (context->callback) {
        context->callback(8, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 9 (average_pool_9)
    if (context->callback) {
        context->callback(9, aot_model_state_started, status, context->user_data);
    }
    status = aot_average_pool_9_init();
    if (context->callback) {
        context->callback(9, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 11 (fully_connected_11)
    if (context->callback) {
        context->callback(11, aot_model_state_started, status, context->user_data);
    }
    status = aot_fully_connected_11_init();
    if (context->callback) {
        context->callback(11, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 12 (softmax_12)
    if (context->callback) {
        context->callback(12, aot_model_state_started, status, context->user_data);
    }
    status = aot_softmax_12_init();
    if (context->callback) {
        context->callback(12, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    return 0;
}

int32_t aot_model_run(aot_model_context_t *context)
{

    int8_t *buffer = model_buffer;

    int32_t status = 0;

    // Running operator 0 (conv_0)
    if (context->callback) {
        context->callback(0, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_0_run(context->input_data[0], (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(0, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 1 (depthwise_conv_1)
    if (context->callback) {
        context->callback(1, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_1_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 8000));
    if (context->callback) {
        context->callback(1, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 2 (conv_2)
    if (context->callback) {
        context->callback(2, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_2_run((int8_t *)(buffer + 8000), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(2, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 3 (depthwise_conv_3)
    if (context->callback) {
        context->callback(3, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_3_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 8000));
    if (context->callback) {
        context->callback(3, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 4 (conv_4)
    if (context->callback) {
        context->callback(4, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_4_run((int8_t *)(buffer + 8000), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(4, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 5 (depthwise_conv_5)
    if (context->callback) {
        context->callback(5, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_5_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 8000));
    if (context->callback) {
        context->callback(5, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 6 (conv_6)
    if (context->callback) {
        context->callback(6, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_6_run((int8_t *)(buffer + 8000), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(6, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 7 (depthwise_conv_7)
    if (context->callback) {
        context->callback(7, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_7_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 8000));
    if (context->callback) {
        context->callback(7, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 8 (conv_8)
    if (context->callback) {
        context->callback(8, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_8_run((int8_t *)(buffer + 8000), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(8, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 9 (average_pool_9)
    if (context->callback) {
        context->callback(9, aot_model_state_started, status, context->user_data);
    }
    status = aot_average_pool_9_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 8000));
    if (context->callback) {
        context->callback(9, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 11 (fully_connected_11)
    if (context->callback) {
        context->callback(11, aot_model_state_started, status, context->user_data);
    }
    status = aot_fully_connected_11_run((int8_t *)(buffer + 8000), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(11, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 12 (softmax_12)
    if (context->callback) {
        context->callback(12, aot_model_state_started, status, context->user_data);
    }
    status = aot_softmax_12_run((int8_t *)(buffer + 0), context->output_data[0]);
    if (context->callback) {
        context->callback(12, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    return 0;

}
