/******************************************************************************
 * @file        aot_model.c
 * @brief       Autogenerated HeliosAOT test case
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   This file is used to verify the correctness of the generated AOT C module.
 *
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdint.h>
#include <stdlib.h>
#include <math.h>
#include "ns_ambiqsuite_harness.h"
#include "aot_model.h"
#include "aot_test_case.h"

static int8_t aot_test_stimulus_input_0[490] = {
  84, 85, 85, 83, 84, 84, 84, 84, 83, 83, 84, 83, 84, 84, 83, 84, 83, 84, 83, 83, 
  84, 84, 84, 85, 85, 85, 84, 85, 84, 84, 84, 83, 84, 84, 84, 85, 83, 85, 84, 84, 
  85, 84, 84, 83, 84, 85, 84, 84, 85, 84, 83, 83, 84, 84, 83, 83, 84, 84, 83, 84, 
  84, 83, 83, 83, 84, 84, 85, 83, 83, 85, 84, 83, 84, 85, 84, 84, 83, 84, 83, 84, 
  85, 84, 84, 84, 83, 84, 83, 84, 84, 83, 83, 85, 84, 85, 84, 84, 84, 83, 84, 84, 
  84, 84, 84, 84, 84, 84, 83, 84, 84, 84, 84, 84, 83, 85, 84, 84, 83, 83, 85, 84, 
  84, 83, 84, 84, 83, 84, 84, 84, 83, 84, 84, 83, 84, 84, 84, 84, 83, 84, 84, 83, 
  84, 84, 85, 84, 84, 84, 83, 84, 83, 84, 84, 83, 84, 84, 83, 84, 84, 84, 84, 84, 
  84, 84, 83, 84, 85, 83, 84, 84, 84, 85, 84, 83, 83, 84, 84, 84, 84, 85, 84, 85, 
  84, 84, 83, 84, 84, 84, 84, 83, 84, 84, 83, 83, 84, 84, 83, 84, 85, 84, 85, 85, 
  84, 83, 84, 83, 84, 83, 84, 83, 84, 84, 85, 84, 84, 84, 85, 84, 84, 83, 84, 84, 
  85, 83, 85, 83, 83, 84, 83, 85, 83, 83, 83, 83, 83, 83, 84, 84, 83, 84, 83, 84, 
  83, 84, 84, 83, 84, 84, 84, 84, 83, 84, 85, 84, 83, 84, 85, 84, 84, 85, 84, 84, 
  84, 84, 84, 83, 84, 84, 83, 84, 84, 84, 85, 83, 84, 83, 84, 83, 84, 84, 85, 83, 
  83, 83, 84, 84, 84, 84, 84, 84, 83, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 
  84, 83, 84, 84, 84, 85, 84, 83, 84, 84, 84, 83, 84, 84, 83, 84, 83, 84, 85, 83, 
  84, 84, 83, 84, 84, 83, 84, 84, 84, 83, 84, 85, 84, 85, 85, 83, 83, 83, 84, 84, 
  84, 83, 83, 84, 83, 84, 85, 84, 84, 84, 83, 83, 84, 84, 84, 83, 84, 83, 83, 84, 
  85, 84, 84, 83, 84, 84, 85, 85, 83, 83, 84, 83, 84, 84, 83, 83, 84, 83, 84, 84, 
  85, 84, 83, 85, 84, 83, 84, 84, 84, 83, 84, 83, 84, 84, 84, 83, 83, 83, 84, 83, 
  83, 83, 83, 84, 85, 84, 83, 83, 83, 84, 83, 85, 83, 84, 85, 84, 84, 84, 84, 83, 
  84, 84, 83, 84, 84, 84, 85, 84, 84, 83, 84, 84, 84, 84, 84, 84, 83, 83, 83, 84, 
  84, 83, 84, 85, 84, 83, 84, 84, 84, 84, 83, 83, 84, 84, 84, 84, 83, 84, 84, 83, 
  85, 83, 84, 84, 84, 84, 84, 84, 83, 84, 84, 84, 84, 83, 84, 84, 84, 83, 84, 84, 
  83, 83, 84, 83, 84, 83, 84, 85, 84, 83
};
static int8_t aot_test_stimulus_output_0[12];
static int8_t aot_test_stimulus_golden_0[12] = {
  -120, -120, -123, -124, -120, -120, -125, -110, -119, -124, -128, 55
};

static const void *aot_test_stimulus_golden[] = {
    aot_test_stimulus_golden_0
};



static void aot_test_stimulus_callback(
    int32_t op,
    aot_operator_state_e state,
    int32_t status,
    void *user_data
) {
    if (state == aot_model_state_finished) {
        ns_lp_printf("Operation %d finished with status %d\n", op, status);
    }
}

aot_model_context_t aot_test_stimulus_context = {
    .input_data = {
       aot_test_stimulus_input_0
    },
    .output_data = {
       aot_test_stimulus_output_0
    },
    .callback = aot_test_stimulus_callback,
    .user_data = NULL
};

int32_t aot_test_case_init(void)
{
    return aot_model_init(&aot_test_stimulus_context);
}

int32_t aot_test_case_run(void)
{
    int32_t result = 0;

    result = aot_model_run(&aot_test_stimulus_context);
    if (result != 0) {
        ns_lp_printf("Model run failed with status %d\n", result);
        return result;
    }

    for (int j = 0; j < aot_outputs_len[0]; j++) {
        float act = aot_test_stimulus_output_0[j];
        float exp = aot_test_stimulus_golden_0[j];
        float diff = fabs(act - exp);
        if (diff > 1.0) {
            ns_lp_printf("Output mismatch at index [0][%d]: expected %f, got %f\n", j, exp, act);
            result = 1;
        }
    }


    if (result == 0) {
        ns_lp_printf("Test passed!\n");
    } else {
        ns_lp_printf("Test failed!\n");
    }
    return result;

}
