/******************************************************************************
 * @file        aot_softmax_12.c
 * @brief       Autogenerated AOT SOFTMAX kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   This kernel represents node #12 in the corresponding graph.
 *
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_softmax_12.h"

// Softmax parameters
static const int32_t softmax_12_num_rows = 1;
static const int32_t softmax_12_row_size = 12;
static const int32_t softmax_12_input_multiplier = 1242899200;
static const int32_t softmax_12_input_shift = 24;
static const int32_t softmax_12_diff_min = -124;

int32_t
aot_softmax_12_init(void)
{
    return 0;
}

int32_t
aot_softmax_12_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    arm_softmax_s8(
        input,
        softmax_12_num_rows,
        softmax_12_row_size,
        softmax_12_input_multiplier,
        softmax_12_input_shift,
        softmax_12_diff_min,
        output
    );
    return 0;

}
