/******************************************************************************
 * @file        aot_model.c
 * @brief       Autogenerated AOT model
 * @details     This model was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   Subgraph: main.
 *   Model Description: MLIR Converted.
 * @version     v1.0.0
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include <stdint.h>
#include <math.h>
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "ns_ambiqsuite_harness.h"
#include "aot_resource_variables.h"
#include "aot_model.h"
#include "aot_conv_0.h"
#include "aot_depthwise_conv_1.h"
#include "aot_conv_2.h"
#include "aot_depthwise_conv_3.h"
#include "aot_conv_4.h"
#include "aot_depthwise_conv_5.h"
#include "aot_conv_6.h"
#include "aot_depthwise_conv_7.h"
#include "aot_conv_8.h"
#include "aot_depthwise_conv_9.h"
#include "aot_conv_10.h"
#include "aot_depthwise_conv_11.h"
#include "aot_conv_12.h"
#include "aot_depthwise_conv_13.h"
#include "aot_conv_14.h"
#include "aot_depthwise_conv_15.h"
#include "aot_conv_16.h"
#include "aot_depthwise_conv_17.h"
#include "aot_conv_18.h"
#include "aot_depthwise_conv_19.h"
#include "aot_conv_20.h"
#include "aot_depthwise_conv_21.h"
#include "aot_conv_22.h"
#include "aot_depthwise_conv_23.h"
#include "aot_conv_24.h"
#include "aot_depthwise_conv_25.h"
#include "aot_conv_26.h"
#include "aot_average_pool_27.h"
#include "aot_fully_connected_29.h"
#include "aot_softmax_30.h"

const int32_t aot_inputs_len[1] = {
    27648
};

const int32_t aot_inputs_zero_point[1] = {
    -128
};

const float aot_inputs_scale[1] = {
    0.003921568859368563
};

const int32_t aot_outputs_len[1] = {
    2
};

const int32_t aot_outputs_zero_point[1] = {
    -128
};

const float aot_outputs_scale[1] = {
    0.00390625
};


alignas(16) static int8_t model_buffer[73728];


int32_t aot_model_init(aot_model_context_t *context)
{

    int32_t status = 0;

    // Initializing operator 0 (conv_0)
    if (context->callback) {
        context->callback(0, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_0_init();
    if (context->callback) {
        context->callback(0, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 1 (depthwise_conv_1)
    if (context->callback) {
        context->callback(1, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_1_init();
    if (context->callback) {
        context->callback(1, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 2 (conv_2)
    if (context->callback) {
        context->callback(2, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_2_init();
    if (context->callback) {
        context->callback(2, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 3 (depthwise_conv_3)
    if (context->callback) {
        context->callback(3, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_3_init();
    if (context->callback) {
        context->callback(3, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 4 (conv_4)
    if (context->callback) {
        context->callback(4, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_4_init();
    if (context->callback) {
        context->callback(4, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 5 (depthwise_conv_5)
    if (context->callback) {
        context->callback(5, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_5_init();
    if (context->callback) {
        context->callback(5, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 6 (conv_6)
    if (context->callback) {
        context->callback(6, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_6_init();
    if (context->callback) {
        context->callback(6, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 7 (depthwise_conv_7)
    if (context->callback) {
        context->callback(7, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_7_init();
    if (context->callback) {
        context->callback(7, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 8 (conv_8)
    if (context->callback) {
        context->callback(8, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_8_init();
    if (context->callback) {
        context->callback(8, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 9 (depthwise_conv_9)
    if (context->callback) {
        context->callback(9, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_9_init();
    if (context->callback) {
        context->callback(9, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 10 (conv_10)
    if (context->callback) {
        context->callback(10, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_10_init();
    if (context->callback) {
        context->callback(10, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 11 (depthwise_conv_11)
    if (context->callback) {
        context->callback(11, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_11_init();
    if (context->callback) {
        context->callback(11, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 12 (conv_12)
    if (context->callback) {
        context->callback(12, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_12_init();
    if (context->callback) {
        context->callback(12, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 13 (depthwise_conv_13)
    if (context->callback) {
        context->callback(13, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_13_init();
    if (context->callback) {
        context->callback(13, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 14 (conv_14)
    if (context->callback) {
        context->callback(14, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_14_init();
    if (context->callback) {
        context->callback(14, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 15 (depthwise_conv_15)
    if (context->callback) {
        context->callback(15, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_15_init();
    if (context->callback) {
        context->callback(15, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 16 (conv_16)
    if (context->callback) {
        context->callback(16, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_16_init();
    if (context->callback) {
        context->callback(16, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 17 (depthwise_conv_17)
    if (context->callback) {
        context->callback(17, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_17_init();
    if (context->callback) {
        context->callback(17, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 18 (conv_18)
    if (context->callback) {
        context->callback(18, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_18_init();
    if (context->callback) {
        context->callback(18, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 19 (depthwise_conv_19)
    if (context->callback) {
        context->callback(19, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_19_init();
    if (context->callback) {
        context->callback(19, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 20 (conv_20)
    if (context->callback) {
        context->callback(20, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_20_init();
    if (context->callback) {
        context->callback(20, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 21 (depthwise_conv_21)
    if (context->callback) {
        context->callback(21, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_21_init();
    if (context->callback) {
        context->callback(21, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 22 (conv_22)
    if (context->callback) {
        context->callback(22, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_22_init();
    if (context->callback) {
        context->callback(22, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 23 (depthwise_conv_23)
    if (context->callback) {
        context->callback(23, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_23_init();
    if (context->callback) {
        context->callback(23, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 24 (conv_24)
    if (context->callback) {
        context->callback(24, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_24_init();
    if (context->callback) {
        context->callback(24, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 25 (depthwise_conv_25)
    if (context->callback) {
        context->callback(25, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_25_init();
    if (context->callback) {
        context->callback(25, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 26 (conv_26)
    if (context->callback) {
        context->callback(26, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_26_init();
    if (context->callback) {
        context->callback(26, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 27 (average_pool_27)
    if (context->callback) {
        context->callback(27, aot_model_state_started, status, context->user_data);
    }
    status = aot_average_pool_27_init();
    if (context->callback) {
        context->callback(27, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 29 (fully_connected_29)
    if (context->callback) {
        context->callback(29, aot_model_state_started, status, context->user_data);
    }
    status = aot_fully_connected_29_init();
    if (context->callback) {
        context->callback(29, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 30 (softmax_30)
    if (context->callback) {
        context->callback(30, aot_model_state_started, status, context->user_data);
    }
    status = aot_softmax_30_init();
    if (context->callback) {
        context->callback(30, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    return 0;
}

int32_t aot_model_run(aot_model_context_t *context)
{

    int8_t *buffer = model_buffer;

    int32_t status = 0;

    // Running operator 0 (conv_0)
    if (context->callback) {
        context->callback(0, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_0_run(context->input_data[0], (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(0, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 1 (depthwise_conv_1)
    if (context->callback) {
        context->callback(1, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_1_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 18432));
    if (context->callback) {
        context->callback(1, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 2 (conv_2)
    if (context->callback) {
        context->callback(2, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_2_run((int8_t *)(buffer + 18432), (int8_t *)(buffer + 36864));
    if (context->callback) {
        context->callback(2, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 3 (depthwise_conv_3)
    if (context->callback) {
        context->callback(3, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_3_run((int8_t *)(buffer + 36864), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(3, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 4 (conv_4)
    if (context->callback) {
        context->callback(4, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_4_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 9216));
    if (context->callback) {
        context->callback(4, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 5 (depthwise_conv_5)
    if (context->callback) {
        context->callback(5, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_5_run((int8_t *)(buffer + 9216), (int8_t *)(buffer + 27648));
    if (context->callback) {
        context->callback(5, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 6 (conv_6)
    if (context->callback) {
        context->callback(6, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_6_run((int8_t *)(buffer + 27648), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(6, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 7 (depthwise_conv_7)
    if (context->callback) {
        context->callback(7, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_7_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 18432));
    if (context->callback) {
        context->callback(7, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 8 (conv_8)
    if (context->callback) {
        context->callback(8, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_8_run((int8_t *)(buffer + 18432), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(8, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 9 (depthwise_conv_9)
    if (context->callback) {
        context->callback(9, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_9_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 9216));
    if (context->callback) {
        context->callback(9, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 10 (conv_10)
    if (context->callback) {
        context->callback(10, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_10_run((int8_t *)(buffer + 9216), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(10, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 11 (depthwise_conv_11)
    if (context->callback) {
        context->callback(11, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_11_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 9216));
    if (context->callback) {
        context->callback(11, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 12 (conv_12)
    if (context->callback) {
        context->callback(12, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_12_run((int8_t *)(buffer + 9216), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(12, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 13 (depthwise_conv_13)
    if (context->callback) {
        context->callback(13, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_13_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 4608));
    if (context->callback) {
        context->callback(13, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 14 (conv_14)
    if (context->callback) {
        context->callback(14, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_14_run((int8_t *)(buffer + 4608), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(14, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 15 (depthwise_conv_15)
    if (context->callback) {
        context->callback(15, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_15_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 4608));
    if (context->callback) {
        context->callback(15, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 16 (conv_16)
    if (context->callback) {
        context->callback(16, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_16_run((int8_t *)(buffer + 4608), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(16, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 17 (depthwise_conv_17)
    if (context->callback) {
        context->callback(17, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_17_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 4608));
    if (context->callback) {
        context->callback(17, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 18 (conv_18)
    if (context->callback) {
        context->callback(18, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_18_run((int8_t *)(buffer + 4608), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(18, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 19 (depthwise_conv_19)
    if (context->callback) {
        context->callback(19, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_19_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 4608));
    if (context->callback) {
        context->callback(19, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 20 (conv_20)
    if (context->callback) {
        context->callback(20, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_20_run((int8_t *)(buffer + 4608), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(20, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 21 (depthwise_conv_21)
    if (context->callback) {
        context->callback(21, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_21_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 4608));
    if (context->callback) {
        context->callback(21, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 22 (conv_22)
    if (context->callback) {
        context->callback(22, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_22_run((int8_t *)(buffer + 4608), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(22, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 23 (depthwise_conv_23)
    if (context->callback) {
        context->callback(23, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_23_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 4608));
    if (context->callback) {
        context->callback(23, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 24 (conv_24)
    if (context->callback) {
        context->callback(24, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_24_run((int8_t *)(buffer + 4608), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(24, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 25 (depthwise_conv_25)
    if (context->callback) {
        context->callback(25, aot_model_state_started, status, context->user_data);
    }
    status = aot_depthwise_conv_25_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 2304));
    if (context->callback) {
        context->callback(25, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 26 (conv_26)
    if (context->callback) {
        context->callback(26, aot_model_state_started, status, context->user_data);
    }
    status = aot_conv_26_run((int8_t *)(buffer + 2304), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(26, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 27 (average_pool_27)
    if (context->callback) {
        context->callback(27, aot_model_state_started, status, context->user_data);
    }
    status = aot_average_pool_27_run((int8_t *)(buffer + 0), (int8_t *)(buffer + 2304));
    if (context->callback) {
        context->callback(27, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 29 (fully_connected_29)
    if (context->callback) {
        context->callback(29, aot_model_state_started, status, context->user_data);
    }
    status = aot_fully_connected_29_run((int8_t *)(buffer + 2304), (int8_t *)(buffer + 0));
    if (context->callback) {
        context->callback(29, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 30 (softmax_30)
    if (context->callback) {
        context->callback(30, aot_model_state_started, status, context->user_data);
    }
    status = aot_softmax_30_run((int8_t *)(buffer + 0), context->output_data[0]);
    if (context->callback) {
        context->callback(30, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    return 0;

}
