/******************************************************************************
 * @file        aot_depthwise_conv_11.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #11 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_11.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_11_input_dims = { .n = 1, .h = 12, .w = 12, .c = 64 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_11_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 64 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_11_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 64 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_11_output_dims = { .n = 1, .h = 6, .w = 6, .c = 64 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_11_multiplier[64] = {
  1430417073, 2026294151, 1927609748, 1797152475, 1162569442, 1119295637, 1425129537, 1091985597, 1648149135, 1389213699, 1543034853, 1851835543, 1472114639, 1795530575, 1634699063, 1322203584, 1646078939, 1621652095, 1186749834, 1889616454, 
  1598229674, 1520488419, 1628810559, 1715451832, 1181401885, 1256965347, 2118542821, 1180362221, 2032146010, 1875052606, 1521815631, 1172902746, 1172552210, 1206046262, 2008445409, 1683982784, 1264070189, 1214605814, 1427533293, 1137788550, 
  1310875691, 1557357283, 1958275515, 1109410864, 1545072150, 1800790129, 1239356500, 1280476748, 1147973631, 1730477909, 1703841076, 1186770557, 2131646573, 1494170276, 1307423607, 1987741336, 1973631638, 1797463321, 2086002966, 1143645209, 
  1758650121, 1662556917, 1215268835, 1756125422
};
static const int32_t dw_11_shift[64] = {
  -7, -8, -8, -5, -7, -7, -7, -7, -7, -6, -8, -8, -5, -5, -8, -7, -8, -8, -8, -8, 
  -5, -7, -7, -7, -7, -7, -8, -7, -7, -8, -7, -6, -6, -7, -8, -8, -6, -6, -7, -7, 
  -7, -7, -8, -7, -8, -8, -7, -3, -6, -5, -7, -7, -8, -7, -7, -8, -7, -7, -9, -7, 
  -7, -8, -7, -7
};

// Offsets and activation parameters.
static const int32_t dw_11_input_zero_point = -128;
static const int32_t dw_11_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_11_weights[] = {
  -24, -69, 115, -127, -11, -16, -18, -9, 0, 101, 52, -24, -106, 5, 83, -93, -89, 39, 83, 33, 
  46, 56, -15, 72, 43, -113, 66, -6, -62, 43, 24, 14, 103, 51, -31, 54, -127, 44, -91, 99, 
  -46, 127, 101, 89, -100, -28, -22, -23, -36, 56, 55, -41, -77, 23, 90, 86, 127, 42, 15, 26, 
  -57, 43, 15, -127, 127, -118, 5, -96, 57, -127, -21, 31, -71, 127, 35, -35, 0, -35, 103, 58, 
  -127, 123, 58, -13, 93, 123, 44, 104, 78, -34, 28, 24, -127, 67, 116, 68, 127, 38, -14, 34, 
  6, 81, -93, 127, -59, -9, 89, 127, -77, -127, 17, -55, -1, 87, -17, -127, -127, -29, 17, 127, 
  82, 85, 68, 120, -104, 68, 100, -97, 120, -45, -64, -99, 62, 21, 4, -127, -127, 67, 47, -41, 
  48, -95, 66, 127, -98, 127, 2, -59, 54, 55, 55, 63, 50, 50, -19, 19, -84, 24, 62, 71, 
  1, -127, 7, 10, 21, 83, 3, 67, -72, -31, -10, 106, -40, -89, 47, 12, 10, 60, -127, -31, 
  -78, -127, -127, 62, 9, 85, 90, 111, -61, 39, 104, -45, -76, -127, 121, -81, 88, -112, 3, 71, 
  -17, 75, 94, -120, -127, -32, 72, -81, -73, 39, 114, -76, 82, 95, 80, 102, 69, -72, 127, 21, 
  -79, 103, 91, -104, 23, 78, 127, 99, -101, -127, -127, 57, -10, -52, 113, 63, -95, -113, 60, -9, 
  -104, 98, 88, 86, -84, 69, 95, 87, 40, -99, 66, 53, -3, 54, 62, 39, 57, -34, 109, -122, 
  127, 58, 56, 36, -75, 113, 127, -74, -68, 42, 127, -25, -114, 91, 127, -108, 127, 127, 126, 127, 
  127, 73, 110, 104, -126, 127, 127, -50, 24, 94, 114, 127, 27, -90, -39, 76, -86, 52, 127, 123, 
  -127, -123, 127, -53, -103, 127, 43, -17, -111, 110, -69, 110, -93, 36, 127, 127, 9, 127, 127, -36, 
  99, 23, 18, 50, 91, 82, 85, -72, -49, 34, 58, -76, 4, -35, 53, 95, -41, 86, 87, -127, 
  68, 32, 71, 58, 64, 127, -11, 127, -91, 73, 68, 47, -84, -115, 44, 22, -1, 5, 54, 35, 
  -118, -11, -28, 109, -26, -60, 82, -41, 3, 55, -123, 24, -74, 17, -98, 64, -53, 127, 114, 110, 
  24, 63, 93, -63, -77, -117, 32, -30, 81, -109, -127, 47, -21, 14, 85, -59, -40, 20, 9, 1, 
  -98, -11, 62, -105, 41, 43, 96, 20, 40, -17, 31, 24, -17, 94, 45, -52, -31, 47, 113, 59, 
  -78, 42, -116, -6, 22, -8, 70, 55, -75, -75, 102, -13, -65, 56, 10, 97, -56, -54, 43, 38, 
  -103, -126, 106, 10, 103, 30, 71, 81, -32, -33, 127, -8, 90, 94, -54, -18, -109, 36, 122, -127, 
  55, -127, 26, -100, -124, -7, 109, -114, 73, 19, 127, 20, 64, 103, 63, 63, -33, 91, 60, -127, 
  -25, 62, 111, 94, 39, 0, -28, 5, -51, -62, 67, 89, -109, -46, 125, -127, -127, 55, 83, -21, 
  -52, -3, -72, 22, -32, -101, 111, 19, 127, 55, 58, 89, 5, 69, 79, 9, 27, 7, 9, -58, 
  -69, 37, 38, -127, -76, -57, 6, 18, -29, 30, 123, -83, 48, 4, 67, -10, 47, 109, 21, 75, 
  11, 42, 26, -80, -77, -4, 46, 16, 2, -18, 1, 21, -127, -112, 14, 28, -36, -13, 29, -114, 
  -12, 18, -98, -29, -7, -27, -63, -10, -22, 14, 26, -1, 45, 26, 13, 58
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_11_bias[] = {
  -1479, 9944, -434, 1837, -5117, -577, 197, 711, 10279, -670, -9031, 10509, 2416, -578, -5517, -1395, 16288, -9296, -10300, 13592, 
  14, -651, -2908, -2118, -3054, 203, -6395, -3608, 14674, -2819, -4765, 5024, -1931, -805, -3280, -815, 4334, -1312, 10166, -2772, 
  10462, -2073, -6587, -10116, 18390, 17714, -4264, -215, 8907, -119, 57, -390, 15620, -2427, 1380, -5181, 324, -1703, -3909, -3993, 
  1480, -3968, -5178, 1064
};
#else
static NS_PUT_IN_TCM int32_t *dw_11_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_11_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context dw_11_context = {
    .buf = dw_11_scratch_buffer,
    .size = sizeof(dw_11_scratch_buffer),
};


int32_t aot_depthwise_conv_11_init(void)
{
    return 0;
}

const cmsis_nn_per_channel_quant_params dw_11_quant_params = {
    .multiplier = (int32_t*)dw_11_multiplier,
    .shift = (int32_t*)dw_11_shift,
};

const cmsis_nn_dw_conv_params dw_11_dw_conv_params = {
    .input_offset = -dw_11_input_zero_point,
    .output_offset = dw_11_output_zero_point,
    .ch_mult = 1,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_11_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_11_context,
        &dw_11_dw_conv_params,
        &dw_11_quant_params,
        &dw_11_input_dims,
        input,
        &dw_11_filter_dims,
        dw_11_weights,
        &dw_11_bias_dims,
        dw_11_bias,
        &dw_11_output_dims,
        output
    );

}
