/******************************************************************************
 * @file        aot_fully_connected_29.c
 * @brief       Autogenerated AOT FULLY_CONNECTED kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #29 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_fully_connected_29.h"

#define HAS_BIAS 1
#define IS_PER_CHANNEL_QUANTIZATION (0)

// Input dimensions: input shape is [N, H, W, C_IN]
static const cmsis_nn_dims fc_29_input_dims = { .n = 1, .h = 1, .w = 1, .c = 256 };

// Filter dimensions: weights shape is [(H * W * C_IN), 1, 1, C_OUT].
static const cmsis_nn_dims fc_29_filter_dims = { .n = 256, .h = 1, .w = 1, .c = 2 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims fc_29_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 2 };

// Output dimensions: output shape is [N, 1, 1, C_OUT].
static const cmsis_nn_dims fc_29_output_dims = { .n = 1, .h = 1, .w = 1, .c = 2 };

// Quantization parameters (per-channel quantization)
static const int32_t fc_29_multiplier[] = {
  1387987840
};
static const int32_t fc_29_shift[] = {
  -7
};

// Offsets and activation parameters.
static const int32_t fc_29_input_zero_point = -128;
static const int32_t fc_29_filter_zero_point = 0;
static const int32_t fc_29_output_zero_point = -5;

// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t fc_29_weights[] = {
  15, -2, -3, 11, -10, 13, -10, -27, 6, 29, -4, 23, -5, 64, 13, 8, 14, 22, 5, -16, 
  12, 5, 23, 13, 11, 4, 2, 7, 10, 0, -21, -24, -20, -13, 77, -13, -8, 66, -22, 0, 
  1, -1, 7, 68, 16, 12, -27, -24, 20, 10, 65, -4, -4, 10, -9, 2, -124, -13, -3, 7, 
  20, 8, 2, -26, -15, 3, 13, 28, -10, 25, -2, 15, -21, -111, 9, 10, -3, -7, 4, -27, 
  -21, 1, -15, -8, -14, -8, 8, 55, 26, 13, -1, -31, 21, -16, 9, -96, -3, -10, 12, 43, 
  2, -22, -5, -5, -11, -3, -5, 2, -7, 8, -8, 7, -3, -5, 24, -17, -30, -18, -21, 9, 
  6, 7, -14, -8, 15, 0, 24, 10, 13, -2, -19, 2, -16, -22, 5, 0, -1, 16, -9, -13, 
  -23, 9, -12, -77, -9, -3, -5, -3, 10, 54, 13, 4, 29, -22, 16, 1, 20, 4, 11, 5, 
  13, -1, 20, 0, 4, -6, 9, 8, 4, -5, 10, 15, 3, -4, -19, -2, -8, -54, -18, 8, 
  5, 4, -17, -8, 7, 9, 11, -10, -20, 63, -16, 2, -15, 9, 12, 16, -27, -12, 11, 8, 
  -73, -74, 5, 1, 7, 11, 5, -47, -1, 3, -9, 19, 9, 6, 55, 23, 18, -12, 27, 4, 
  14, 21, 89, -13, 14, 23, -12, -1, -9, 18, -19, -10, 5, -11, 2, 1, 0, 3, -11, -86, 
  4, 6, -27, 29, -3, 18, -8, 12, -20, -36, -3, 11, -24, 45, 29, -11, 15, -2, -3, 12, 
  -10, 13, -10, -27, 7, 29, -5, 23, -5, -72, 13, 8, 14, 22, 5, -16, 12, 3, 23, 13, 
  11, 4, 3, 5, 10, 0, -21, -24, -20, -13, -63, -13, -8, -70, -22, -1, 1, 0, 7, -64, 
  16, 13, -27, -24, 20, 10, -65, -4, -3, 10, -9, 2, 127, -12, -3, 7, 20, 8, 2, -26, 
  -15, 2, 13, 28, -10, 25, -2, 15, -21, 104, 9, 10, -3, -7, 3, -27, -21, -22, -15, -9, 
  -14, -8, 8, -58, 23, 13, -1, -31, 21, -16, 9, 112, -3, -10, 12, -50, 2, -22, -5, -5, 
  -11, -3, -5, 2, -7, 9, -8, 7, -3, -7, 24, -16, -30, -18, -21, 9, 6, 7, -14, -8, 
  15, 0, 24, 10, 13, -2, -19, 2, -15, -22, 5, 0, 0, 16, -10, -13, -22, 9, -11, 78, 
  -9, -3, -5, -9, 11, -36, 13, 4, 29, -22, 16, 1, 20, 3, 11, 5, 13, -1, 20, 0, 
  4, -6, 9, 7, 8, -6, 10, 15, 3, -4, -19, -2, -8, 58, -18, 8, 5, 4, -17, -9, 
  7, 9, 11, -10, -20, -69, -16, 2, -15, 9, 12, 16, -27, -12, 12, 8, 67, 82, 5, 2, 
  7, 11, 5, 56, -1, 3, -9, 18, 9, 4, -67, 23, 17, -12, 27, 4, 14, 21, -77, -13, 
  14, 23, -12, 0, -10, 16, -20, -10, 4, -11, 2, 1, 0, 4, -15, 99, 4, 6, -27, 29, 
  -3, 18, -7, 12, -19, 35, -3, 11, -24, -46, 29, -11
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t fc_29_bias[] = {
  1463, -1463
};
#else
static NS_PUT_IN_TCM int32_t *fc_29_bias = NULL;
#endif


alignas(16) static NS_PUT_IN_TCM int32_t fc_29_kernel_sum[2];

static cmsis_nn_context fc_29_context = {
    .buf = (void *)fc_29_kernel_sum,
    .size = sizeof(fc_29_kernel_sum),
};

static cmsis_nn_fc_params fc_29_fc_params = {
    .input_offset = -fc_29_input_zero_point,
    .filter_offset = -fc_29_filter_zero_point,
    .output_offset = fc_29_output_zero_point,
    .activation.min = -128,
    .activation.max = 127,
};

#if IS_PER_CHANNEL_QUANTIZATION

const cmsis_nn_per_channel_quant_params fc_29_quant_params = {
    .multiplier = (int32_t*)fc_29_multiplier,
    .shift = (int32_t*)fc_29_shift,
};

#else

const cmsis_nn_per_tensor_quant_params fc_29_quant_params = {
    .multiplier = fc_29_multiplier[0],
    .shift = fc_29_shift[0],
};

#endif // IS_PER_CHANNEL_QUANTIZATION

int32_t aot_fully_connected_29_init(void)
{
    // Precompute kernel sums for each output channel.
    arm_vector_sum_s8(
        (int32_t *)fc_29_kernel_sum,
        fc_29_filter_dims.n,
        fc_29_filter_dims.c,
        fc_29_weights,
        fc_29_fc_params.input_offset,
        fc_29_fc_params.filter_offset,
        fc_29_bias
    );
    return 0;
}

int32_t aot_fully_connected_29_run(const int8_t* __restrict input, int8_t* __restrict output)
{

#if IS_PER_CHANNEL_QUANTIZATION

    return arm_fully_connected_per_channel_s8(
        &fc_29_context,
        &fc_29_fc_params,
        &fc_29_quant_params,
        &fc_29_input_dims,
        input,
        &fc_29_filter_dims,
        fc_29_weights,
        &fc_29_bias_dims,
        fc_29_bias,
        &fc_29_output_dims,
        output
    );

#else

    return arm_fully_connected_s8(
        &fc_29_context,
        &fc_29_fc_params,
        &fc_29_quant_params,
        &fc_29_input_dims,
        input,
        &fc_29_filter_dims,
        fc_29_weights,
        &fc_29_bias_dims,
        fc_29_bias,
        &fc_29_output_dims,
        output
    );

#endif // IS_PER_CHANNEL_QUANTIZATION

}
