/******************************************************************************
 * @file        aot_depthwise_conv_7.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #7 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_7.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_7_input_dims = { .n = 1, .h = 24, .w = 24, .c = 32 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_7_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 32 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_7_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 32 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_7_output_dims = { .n = 1, .h = 12, .w = 12, .c = 32 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_7_multiplier[32] = {
  1116805413, 1494305519, 1121370940, 1690084744, 1906525973, 1284359072, 1635062873, 1514385068, 1770799560, 1173429631, 1357211117, 1483780611, 1460491508, 1924919614, 1594828194, 1550701066, 1900772606, 1769830208, 1079777995, 1354317281, 
  1416057010, 1957586603, 1483576155, 1802264766, 1618203427, 1853050220, 1376695095, 1931000073, 1073982067, 1516074003, 1927345927, 1367153480
};
static const int32_t dw_7_shift[32] = {
  -5, -7, -5, -7, -6, -6, -7, -7, -7, -5, -7, -6, -7, -7, -7, -7, -7, -6, -6, -7, 
  -7, -7, -7, -8, -7, -7, -7, -8, -6, -8, -8, -6
};

// Offsets and activation parameters.
static const int32_t dw_7_input_zero_point = -128;
static const int32_t dw_7_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_7_weights[] = {
  44, -6, 74, -83, 82, -41, 81, -34, 0, -124, 52, -66, 75, -74, -21, -23, -78, -32, -62, -71, 
  -61, 7, -76, 42, 54, 86, -40, 75, -20, 25, 80, -75, 91, -75, -81, -76, 110, -59, 127, -65, 
  -89, -127, 115, 56, 40, -127, -77, -68, -56, -62, -76, -60, -6, -47, 15, 65, 30, 127, -105, 99, 
  -54, 75, 102, -127, 67, -26, -73, 30, 59, -28, 47, -48, -86, -46, 65, 64, -21, -53, -87, -77, 
  -7, -32, -20, 9, 77, -103, 41, 32, -28, 39, -78, 26, -68, 55, 23, -48, 88, -72, 127, -78, 
  -20, -76, 102, -78, -77, 10, 100, -127, 127, -109, -61, -40, -66, -80, -75, -45, -1, -92, -127, 45, 
  84, 123, -126, 119, -66, 54, 112, -41, 127, -127, -45, 29, -19, -127, 116, -127, -127, 21, 127, 50, 
  100, -118, -127, -124, -127, -127, -127, -127, 109, -112, 57, 124, 121, 94, -127, 127, -127, 127, 127, -81, 
  66, -53, -80, 97, 1, -53, 42, -59, -48, 37, 80, 65, -12, -47, -32, -127, -104, -52, -60, -82, 
  127, -127, 100, 127, 53, 4, -29, 24, -71, 66, 2, -40, 61, -76, 56, -9, -87, -39, 21, -4, 
  -40, 83, 87, -40, 67, -45, -27, -44, -7, -59, -66, -17, 74, -40, -26, -3, 69, 18, -73, 53, 
  -7, 51, 60, 20, 76, -66, -17, 93, -127, -60, 13, -86, -59, 94, 82, -6, 79, -17, -25, -81, 
  -57, -72, -63, -41, 118, -76, 60, 96, 127, -22, -47, 57, -53, 45, 29, -5, 29, -23, -63, 127, 
  -64, -12, 16, -28, -3, 45, 24, 12, 34, 12, -10, -71, -56, -20, -33, -71, 46, -73, 62, 84, 
  103, -45, 31, 17, -43, 9, -13, -16
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_7_bias[] = {
  116, 9317, 1182, 1079, 2366, 8784, 440, 9400, 11013, 202, -7340, -395, -1934, 10160, 6805, 10270, 9382, 13314, 10073, 8164, 
  -4276, 10052, -1347, -4775, -2234, -1176, 14306, -158, 7960, 1353, 1159, 6309
};
#else
static NS_PUT_IN_TCM int32_t *dw_7_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_7_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context dw_7_context = {
    .buf = dw_7_scratch_buffer,
    .size = sizeof(dw_7_scratch_buffer),
};


int32_t aot_depthwise_conv_7_init(void)
{
    return 0;
}

const cmsis_nn_per_channel_quant_params dw_7_quant_params = {
    .multiplier = (int32_t*)dw_7_multiplier,
    .shift = (int32_t*)dw_7_shift,
};

const cmsis_nn_dw_conv_params dw_7_dw_conv_params = {
    .input_offset = -dw_7_input_zero_point,
    .output_offset = dw_7_output_zero_point,
    .ch_mult = 1,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_7_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_7_context,
        &dw_7_dw_conv_params,
        &dw_7_quant_params,
        &dw_7_input_dims,
        input,
        &dw_7_filter_dims,
        dw_7_weights,
        &dw_7_bias_dims,
        dw_7_bias,
        &dw_7_output_dims,
        output
    );

}
