/******************************************************************************
 * @file        aot_depthwise_conv_1.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #1 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_1.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_1_input_dims = { .n = 1, .h = 48, .w = 48, .c = 8 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_1_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 8 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_1_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 8 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_1_output_dims = { .n = 1, .h = 48, .w = 48, .c = 8 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_1_multiplier[8] = {
  1774938322, 1243371083, 1245972338, 1646402194, 1255879271, 1190494641, 1703681304, 1526575410
};
static const int32_t dw_1_shift[8] = {
  -8, -7, -8, -7, -7, -5, -7, -7
};

// Offsets and activation parameters.
static const int32_t dw_1_input_zero_point = -128;
static const int32_t dw_1_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_1_weights[] = {
  -74, -113, -71, -27, -40, -57, 81, 41, -5, 6, -30, -18, -40, 57, 1, 49, -77, -7, -11, -3, 
  25, 49, 47, -26, 108, 78, 16, 17, 52, 23, -103, -14, 127, 44, 75, -1, 33, -127, -127, -127, 
  40, -27, -25, -3, -62, 24, 13, 38, 42, 127, 127, -1, 50, 17, 34, -73, 44, 66, 70, 127, 
  127, 50, -72, -63, -91, -104, -1, -46, -72, -82, 75, 60
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_1_bias[] = {
  -1066, -291, -2269, 2239, -115, 3445, 5252, 6322
};
#else
static NS_PUT_IN_TCM int32_t *dw_1_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_1_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context dw_1_context = {
    .buf = dw_1_scratch_buffer,
    .size = sizeof(dw_1_scratch_buffer),
};


int32_t aot_depthwise_conv_1_init(void)
{
    return 0;
}

const cmsis_nn_per_channel_quant_params dw_1_quant_params = {
    .multiplier = (int32_t*)dw_1_multiplier,
    .shift = (int32_t*)dw_1_shift,
};

const cmsis_nn_dw_conv_params dw_1_dw_conv_params = {
    .input_offset = -dw_1_input_zero_point,
    .output_offset = dw_1_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_1_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_1_context,
        &dw_1_dw_conv_params,
        &dw_1_quant_params,
        &dw_1_input_dims,
        input,
        &dw_1_filter_dims,
        dw_1_weights,
        &dw_1_bias_dims,
        dw_1_bias,
        &dw_1_output_dims,
        output
    );

}
