/******************************************************************************
 * @file        aot_depthwise_conv_5.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #5 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_5.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_5_input_dims = { .n = 1, .h = 24, .w = 24, .c = 32 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_5_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 32 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_5_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 32 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_5_output_dims = { .n = 1, .h = 24, .w = 24, .c = 32 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_5_multiplier[32] = {
  1977545271, 1489544133, 1462272696, 1113542160, 1275734482, 1484223587, 1406050503, 1205329682, 1078033883, 1191826471, 1097082255, 1730110921, 1802777803, 1211544782, 1341010557, 1235199765, 1405155539, 1147167783, 1114508569, 1265305462, 
  1413066815, 1542342207, 1370202786, 1443028595, 1748058732, 1857646138, 1583521780, 1829439645, 2081596562, 1527616618, 1980074938, 1256659381
};
static const int32_t dw_5_shift[32] = {
  -7, -5, -7, -7, -7, -6, -6, -6, -6, -7, -6, -7, -7, -6, -6, -7, -6, -6, -6, -6, 
  -5, -7, -6, -6, -7, -6, -7, -7, -7, -7, -7, -7
};

// Offsets and activation parameters.
static const int32_t dw_5_input_zero_point = -128;
static const int32_t dw_5_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_5_weights[] = {
  0, -127, 7, -12, 7, 114, 6, 68, -111, -7, 7, -30, -38, -42, 28, -47, -70, -73, -24, 127, 
  81, -28, -17, 90, -3, -37, -34, -8, -8, 92, 10, 87, 72, 124, -127, 47, -89, -61, 54, 7, 
  -112, 62, 55, -111, 55, 86, -42, 45, -101, 115, -127, -39, -80, 74, -22, -98, -111, -78, 21, 127, 
  99, 127, -35, 8, -20, 23, 34, -29, 27, -6, -53, 24, -85, -7, -58, 43, 32, 70, 3, 27, 
  -33, 127, -49, -35, -25, 22, -52, -51, 23, 127, 12, 26, -8, -35, 26, -32, 8, 53, 39, -47, 
  16, 127, -14, 18, 48, 8, -98, 11, -47, -127, -74, -4, 127, -59, -13, 93, -116, 39, -37, -55, 
  -24, -18, -47, -50, -69, 99, -93, 83, 127, 14, -94, 127, -98, -92, 127, -79, 127, 127, 127, -127, 
  127, -46, 127, 127, 85, 33, 111, -71, 127, 127, -72, -122, -127, -78, 69, 53, 127, -92, -127, 127, 
  86, -31, -30, 84, -10, -75, -80, -38, 52, -3, 94, 110, 30, 68, -7, 84, -77, 36, 84, -46, 
  30, 11, 127, 127, -19, 96, 127, 107, -49, -103, -32, 44, -104, 84, 74, -41, 73, 23, 0, -21, 
  22, -21, -13, 8, -30, -37, 49, -30, -54, -16, 15, -4, 24, 13, -35, -72, 49, -6, -16, 3, 
  -81, -50, -7, -20, 0, -76, -2, 23, -127, -28, 36, -127, 55, 115, -90, -87, -27, -51, -40, 39, 
  98, -69, -4, 12, -69, 25, -104, -49, -23, -17, 38, -79, 58, -62, -109, 0, 26, -22, -64, 90, 
  -49, -45, -19, -38, -24, 8, -44, 56, -4, -10, 10, -14, -1, -74, 21, -5, -9, -35, 38, 107, 
  10, 4, -12, -28, -48, 17, 1, 29
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_5_bias[] = {
  -4022, -1190, 3563, -4529, 6490, 2210, -680, 3026, -109, -1759, -300, 1686, 202, 2051, -1403, -3368, -171, -32, -351, -846, 
  871, -4029, 3766, 57, 4585, 101, -2373, -475, -394, -94, 7402, -4489
};
#else
static NS_PUT_IN_TCM int32_t *dw_5_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_5_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context dw_5_context = {
    .buf = dw_5_scratch_buffer,
    .size = sizeof(dw_5_scratch_buffer),
};


int32_t aot_depthwise_conv_5_init(void)
{
    return 0;
}

const cmsis_nn_per_channel_quant_params dw_5_quant_params = {
    .multiplier = (int32_t*)dw_5_multiplier,
    .shift = (int32_t*)dw_5_shift,
};

const cmsis_nn_dw_conv_params dw_5_dw_conv_params = {
    .input_offset = -dw_5_input_zero_point,
    .output_offset = dw_5_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_5_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_5_context,
        &dw_5_dw_conv_params,
        &dw_5_quant_params,
        &dw_5_input_dims,
        input,
        &dw_5_filter_dims,
        dw_5_weights,
        &dw_5_bias_dims,
        dw_5_bias,
        &dw_5_output_dims,
        output
    );

}
