/******************************************************************************
 * @file        aot_depthwise_conv_7.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   This kernel represents node #7 in the corresponding graph.
 *
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_7.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#define WEIGHT_SUM_BUFFER_SIZE 256
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_7_input_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_7_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 64 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_7_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 64 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_7_output_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_7_multiplier[64] = {
  1245499324, 2021708468, 1876208089, 1325188464, 1598729909, 1605918323, 1305633077, 2141131275, 1171759477, 1746719341, 2003695361, 1574723363, 2145427927, 1725225812, 1519686186, 2016259725, 2117951231, 1124575500, 2046616471, 1801639759, 
  1159154122, 1672063802, 1338164997, 1080975729, 1410880862, 1767309430, 1301111827, 1584185150, 1663224188, 1218672369, 1749809845, 1710495465, 1336342172, 1390854296, 1811826604, 1380530602, 1173781765, 2037710910, 1884565532, 2052846670, 
  1190845216, 1539715364, 1885930421, 1141038130, 1777548167, 1752818546, 1174930344, 1578116035, 1720287347, 1685584038, 1390238789, 1109472714, 1998071659, 1101556990, 1664121682, 1205680881, 1512822462, 1214391303, 1217392797, 1078342080, 
  1466779135, 1254490022, 1179852051, 1515358182
};
static const int32_t dw_7_shift[64] = {
  -7, -9, -8, -8, -8, -7, -7, -8, -6, -8, -7, -8, -8, -8, -7, -8, -8, -7, -8, -7, 
  -7, -8, -8, -7, -7, -8, -7, -8, -7, -7, -7, -8, -7, -7, -7, -7, -7, -8, -7, -8, 
  -7, -7, -8, -7, -8, -8, -6, -7, -7, -8, -6, -7, -8, -6, -7, -6, -7, -7, -7, -7, 
  -7, -7, -6, -7
};

// Offsets and activation parameters.
static const int32_t dw_7_input_zero_point = -128;
static const int32_t dw_7_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_7_weights[] = {
  102, 127, 118, -120, -107, -127, 99, -127, 127, -52, 57, -31, -110, -121, -41, -108, -77, -127, -110, -104, 
  -60, -37, 93, -85, 49, -127, -40, -105, 50, 110, 57, -45, -42, -54, 124, 68, 103, 94, 104, 63, 
  -77, -127, -102, -103, -112, 53, 127, -1, 105, 127, -45, -97, 76, 58, 91, 127, 87, -65, -69, -127, 
  -100, -115, 119, 119, 107, 44, 63, -127, -106, -71, 100, -98, 32, -108, 84, -60, -127, -115, -127, -127, 
  -55, -85, -50, 45, -16, -63, 64, -127, 41, -86, -98, -65, -127, -27, 75, -103, -45, -127, 91, 31, 
  106, 124, 102, 81, -82, 95, -22, -104, -127, 114, 84, -75, 122, 122, 127, -84, 127, -9, 77, 88, 
  77, -106, -69, -124, -97, 85, 116, 127, 127, 24, 123, 10, -127, 61, 69, -68, -61, -68, 95, -82, 
  -68, -110, 41, -93, -127, -113, -80, 86, -91, -13, 49, -76, 31, -127, -127, -74, 79, -127, 127, -5, 
  -15, -38, 67, -14, 127, 110, 80, 89, -64, -73, -127, -45, -75, 127, 113, -35, 127, 81, -40, -64, 
  120, -64, 101, -37, 96, -36, -127, -51, -34, 35, 127, 72, 10, 95, 29, -75, -47, -5, 3, -77, 
  25, -50, 8, -59, 24, -59, -84, -15, 2, -43, -49, -127, -63, -78, 74, 38, -32, -36, -47, -23, 
  20, 18, 16, -54, -46, 2, 30, 87, 16, 8, 16, 47, -29, -44, -39, 16, -57, 21, 33, 17, 
  22, 33, -9, -38, -8, 31, -47, 25, 16, -35, -18, 14, 14, -127, -3, 30, 11, 39, 15, -68, 
  -14, -36, -11, -67, -9, -59, 0, -66, -14, -42, -67, -17, 21, -39, -81, -21, 9, -42, 39, 17, 
  -59, 53, -46, -10, -88, -24, -8, -54, -55, 21, 31, -47, -6, -34, 20, 80, -26, 29, -23, 9, 
  -43, 12, 18, -67, 15, 35, 18, -57, -16, -38, -37, 27, -10, -37, -14, 46, -2, 25, 8, 22, 
  -42, 109, 13, 49, -44, 29, -15, -25, -63, -15, 9, -42, -17, -72, 85, 5, -10, -11, -66, 40, 
  -92, -35, 40, -59, -37, 20, -38, -16, 53, -116, -19, 37, -17, -4, -127, -74, 23, -4, 47, 79, 
  -103, -45, -31, 39, -25, 10, 22, -52, -15, 21, -24, -45, -26, -34, -47, -54, 3, -28, 2, 12, 
  -34, 55, -18, 23, 71, 92, 116, -94, -70, -64, 127, -73, 117, -127, 86, -126, -59, -127, -111, -85, 
  -86, -76, -51, -35, -126, -127, 127, -111, -84, -99, -101, -55, 68, 66, 116, -127, -95, -57, 58, 127, 
  107, 127, 80, 90, -118, -59, -116, -105, -112, 53, 106, 24, 104, 60, -11, -103, 74, 48, 127, 8, 
  98, -127, -121, -97, -52, 13, 108, 96, 47, 103, 81, -125, -79, -118, 96, -98, 34, -103, 97, -127, 
  -85, -90, 86, -111, -82, -77, -116, 29, -85, -73, 123, -64, -126, -38, -97, -88, -91, -16, 77, -80, 
  -127, -77, 46, 17, 95, 118, 102, 100, -127, 70, -2, -109, -70, 115, 76, -63, 114, 99, 100, -127, 
  54, -37, 104, 53, 127, -105, -105, -93, -123, 107, 104, 107, 14, 47, 127, -7, -69, 46, 62, -15, 
  -49, -43, 127, -110, -90, -31, 126, -127, -95, -45, -127, 64, -127, -73, 114, 34, -127, -118, -80, -127, 
  72, -115, 106, 2, -122, -23, 23, -113, 111, 52, 127, 127, -119, -46, -76, -127, -45, 83, 102, -127, 
  125, 103, -69, -70, 76, -127, 79, -67, 84, -6, -110, -68, -127, 110, 101, 59
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_7_bias[] = {
  -2492, -8434, -4092, 6676, 7389, 2053, -3084, 7358, -1247, 8845, -2530, 7362, 5024, 9570, -289, 7954, 6420, 6368, 5273, 94, 
  4397, 5913, -7233, 3552, 2937, 4887, 6631, 6875, -748, 2192, -2347, 5024, 6292, 3686, -2350, -890, -3736, -3442, -3349, -6784, 
  6222, 106, 5129, 6863, 6943, -3998, -1525, 2892, -2389, -4506, -1055, 8403, -3350, 951, -3446, -1376, -4756, 5490, 7559, 6331, 
  5207, -1963, -1266, -2868
};
#else
static NS_PUT_IN_TCM int32_t *dw_7_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_7_scratch_buffer[SCRATCH_BUFFER_SIZE];
alignas(16) static NS_PUT_IN_TCM int8_t dw_7_weight_sum_buffer[WEIGHT_SUM_BUFFER_SIZE];


static cmsis_nn_context dw_7_ctx = {
    .buf = dw_7_scratch_buffer,
    .size = sizeof(dw_7_scratch_buffer),
};

static cmsis_nn_context dw_7_weight_sum_ctx = {
    .buf = dw_7_weight_sum_buffer,
    .size = sizeof(dw_7_weight_sum_buffer),
};


const cmsis_nn_per_channel_quant_params dw_7_quant_params = {
    .multiplier = (int32_t*)dw_7_multiplier,
    .shift = (int32_t*)dw_7_shift,
};

const cmsis_nn_dw_conv_params dw_7_dw_conv_params = {
    .input_offset = -dw_7_input_zero_point,
    .output_offset = dw_7_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_7_init(void)
{
    return arm_depthwise_convolve_weight_sum(
        (int32_t *)dw_7_weight_sum_buffer,
        NULL, // No scratch buffer required
        dw_7_weights,
        &dw_7_dw_conv_params,
        &dw_7_input_dims,
        &dw_7_filter_dims,
        &dw_7_output_dims,
        dw_7_dw_conv_params.input_offset,
        dw_7_bias
    );
}


int32_t aot_depthwise_conv_7_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_7_ctx,
        &dw_7_weight_sum_ctx,
        &dw_7_dw_conv_params,
        &dw_7_quant_params,
        &dw_7_input_dims,
        input,
        &dw_7_filter_dims,
        dw_7_weights,
        &dw_7_bias_dims,
        dw_7_bias,
        &dw_7_output_dims,
        output
    );

}
