/******************************************************************************
 * @file        aot_model.c
 * @brief       Autogenerated AOT model
 * @details     This model was generated by HeliosAOT v0.2.2 on 2025-06-03.
 *   Subgraph: main.
 *   Model Description: MLIR Converted.
 * @version     v1.0.0
 * @date        2025-06-03
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include <stdint.h>
#include <math.h>
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "ns_ambiqsuite_harness.h"
#include "aot_resource_variables.h"
#include "aot_model.h"
#include "aot_strided_slice_0.h"
#include "aot_strided_slice_1.h"
#include "aot_strided_slice_2.h"
#include "aot_strided_slice_3.h"

const int32_t aot_inputs_len[1] = {
    192
};

const int32_t aot_inputs_zero_point[1] = {
    -1
};

const float aot_inputs_scale[1] = {
    0.007842794992029667
};

const int32_t aot_outputs_len[4] = {
    27, 48, 36, 192
};

const int32_t aot_outputs_zero_point[4] = {
    -1, -1, -1, -1
};

const float aot_outputs_scale[4] = {
    0.007842794992029667, 0.007842794992029667, 0.007842794992029667, 0.007842794992029667
};


alignas(16) static int8_t model_buffer[0];


int32_t aot_model_init(aot_model_context_t *context)
{

    int32_t status = 0;

    // Initializing operator 0 (strided_slice_0)
    if (context->callback) {
        context->callback(0, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_0_init();
    if (context->callback) {
        context->callback(0, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 1 (strided_slice_1)
    if (context->callback) {
        context->callback(1, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_1_init();
    if (context->callback) {
        context->callback(1, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 2 (strided_slice_2)
    if (context->callback) {
        context->callback(2, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_2_init();
    if (context->callback) {
        context->callback(2, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Initializing operator 3 (strided_slice_3)
    if (context->callback) {
        context->callback(3, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_3_init();
    if (context->callback) {
        context->callback(3, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    return 0;
}

int32_t aot_model_run(aot_model_context_t *context)
{

    int8_t *buffer = model_buffer;

    int32_t status = 0;

    // Running operator 0 (strided_slice_0)
    if (context->callback) {
        context->callback(0, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_0_run(context->input_data[0], context->output_data[2]);
    if (context->callback) {
        context->callback(0, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 1 (strided_slice_1)
    if (context->callback) {
        context->callback(1, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_1_run(context->input_data[0], context->output_data[0]);
    if (context->callback) {
        context->callback(1, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 2 (strided_slice_2)
    if (context->callback) {
        context->callback(2, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_2_run(context->input_data[0], context->output_data[1]);
    if (context->callback) {
        context->callback(2, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    // Running operator 3 (strided_slice_3)
    if (context->callback) {
        context->callback(3, aot_model_state_started, status, context->user_data);
    }
    status = aot_strided_slice_3_run(context->input_data[0], context->output_data[3]);
    if (context->callback) {
        context->callback(3, aot_model_state_finished, status, context->user_data);
    }
    if (status != 0) { return status; }

    return 0;

}
