/******************************************************************************
 * @file        aot_softmax_30.c
 * @brief       Autogenerated AOT SOFTMAX kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #30 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_softmax_30.h"

// Softmax parameters
static const int32_t softmax_30_num_rows = 1;
static const int32_t softmax_30_row_size = 2;
static const int32_t softmax_30_input_multiplier = 2011586560;
static const int32_t softmax_30_input_shift = 20;
static const int32_t softmax_30_diff_min = -1984;

int32_t
aot_softmax_30_init(void)
{
    return 0;
}

int32_t
aot_softmax_30_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    arm_softmax_s8(
        input,
        softmax_30_num_rows,
        softmax_30_row_size,
        softmax_30_input_multiplier,
        softmax_30_input_shift,
        softmax_30_diff_min,
        output
    );
    return 0;

}
