/******************************************************************************
 * @file        aot_depthwise_conv_1.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   This kernel represents node #1 in the corresponding graph.
 *
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_1.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#define WEIGHT_SUM_BUFFER_SIZE 256
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_1_input_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_1_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 64 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_1_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 64 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_1_output_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_1_multiplier[64] = {
  1117272080, 1351620567, 1208841889, 1680313023, 1480831180, 1867036575, 1274068427, 1551573551, 1294969724, 1383317958, 1236810790, 1458694841, 1431041453, 1527668729, 1972269723, 1085649278, 1145655177, 1883008410, 1699922209, 1787116075, 
  2034358525, 1870523896, 1303360346, 1162227620, 1943854503, 1401822542, 1203348201, 1837357352, 1599269182, 1757899597, 1081471549, 1540510979, 1264653146, 1386686886, 1200409896, 1368802621, 1087238284, 1193358838, 1651991982, 1445986925, 
  1245546981, 1617319173, 2142376177, 1394652726, 2095469635, 1151724771, 2022842212, 1433810868, 1078765408, 1334169966, 1343470626, 1463716779, 1467283313, 1962296422, 1729111065, 1720207323, 1596415686, 1989330707, 1124519040, 1702538309, 
  1312306067, 1708501555, 1537057119, 1801960675
};
static const int32_t dw_1_shift[64] = {
  -6, -7, -6, -6, -6, -6, -6, -7, -6, -7, -6, -6, -6, -6, -7, -6, -6, -6, -6, -6, 
  -6, -7, -5, -6, -6, -7, -6, -6, -6, -6, -6, -7, -6, -6, -6, -6, -6, -7, -6, -6, 
  -5, -6, -6, -6, -7, -6, -7, -7, -5, -6, -6, -5, -6, -7, -7, -7, -6, -7, -5, -6, 
  -6, -7, -6, -6
};

// Offsets and activation parameters.
static const int32_t dw_1_input_zero_point = -128;
static const int32_t dw_1_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_1_weights[] = {
  42, 1, -63, -42, 35, -45, -9, -63, 127, -127, -30, -51, -71, 45, -33, 4, -46, 22, 54, -45, 
  65, -11, 45, -53, -62, 84, 42, -65, -37, -35, -12, 69, -23, -9, -26, -4, -90, -9, -5, -10, 
  -44, 32, 127, 22, -65, -3, -57, -68, -47, 18, 34, 4, -78, 63, 56, 119, 48, 72, -13, -55, 
  -32, -127, -73, -35, -2, -96, 32, 127, -35, 27, -55, -88, -53, 112, -28, 54, 45, -22, 26, -80, 
  20, 18, -25, -37, 22, 8, -13, -33, 25, -25, 47, 4, 92, 10, 59, -127, 10, 127, 27, -11, 
  -19, -10, -20, -70, 43, -106, -15, 7, -5, -64, -78, -42, 1, -127, -63, 17, -79, -100, 67, 10, 
  -6, -126, -7, -13, 32, 3, -35, -34, 30, -127, -76, 2, 127, 10, 127, -13, -88, 78, 124, -70, 
  -39, -73, -41, 6, 77, -115, 125, 30, -8, -21, 19, 15, -24, -48, -76, 96, 57, 28, 120, -48, 
  -60, 85, -9, -120, -31, -100, -69, 22, 5, 68, -40, -87, 3, 80, 18, -91, -102, -48, -117, -83, 
  37, -127, -70, -127, 127, -83, 3, -7, -74, 61, -27, 127, -68, -58, -47, 3, -55, 127, -73, -118, 
  -71, -118, -65, 60, -127, 49, 32, -40, 74, 51, 37, 127, 13, -52, -15, 127, -29, 117, 19, 75, 
  -72, -50, -66, 52, -32, -7, -127, -22, -118, 42, 5, -23, -42, 25, -50, 35, 127, -27, -127, -106, 
  37, 22, -5, -12, -68, 5, 127, -116, 38, 80, 127, -26, 81, -100, -47, -31, -34, -85, 22, -80, 
  -28, -19, -26, -67, -45, 91, 127, -65, 106, -14, -81, 121, -64, -25, -77, -80, -22, 35, -42, -40, 
  29, -70, -85, 46, -44, -16, 21, -117, 23, -23, 46, -14, -18, -81, -2, -36, 75, -59, -42, -35, 
  -64, 127, -78, -55, 4, 118, -44, -45, -18, -3, 116, -38, -10, 75, -34, -2, -5, -52, -37, 77, 
  15, -40, -114, 54, 122, -33, -42, 53, 43, 0, -51, 0, -37, -127, -31, -76, 34, -127, 127, 126, 
  -87, -88, -38, -34, -127, 1, -81, 67, -40, 21, 127, -51, -67, -5, -1, -127, 18, 15, -127, 30, 
  7, 127, 31, -127, -23, -108, 50, 8, 127, -109, -122, 127, 127, -17, -26, 80, 12, -127, 80, -98, 
  -127, 39, 127, 80, 59, -102, -53, -8, -33, -16, -52, -127, -41, -3, -7, 25, 61, -13, 127, -99, 
  74, -34, 2, -24, 29, -54, -3, -26, 0, -44, -11, 1, 7, 127, -50, -29, 127, 0, -62, 68, 
  127, 122, 1, -27, 5, -15, -7, 7, 5, -27, -58, -79, 1, -20, 20, 2, 1, 30, -101, -101, 
  16, -99, -60, 4, -4, 45, -3, 14, -127, -19, 30, 52, -31, 36, -8, 37, 98, 77, -40, -68, 
  -75, -11, -65, 127, 119, -30, -68, -17, -25, 46, 127, 52, -43, -26, -127, -51, 62, -21, -68, -66, 
  28, -18, 99, -8, -21, -127, 12, 1, -8, 78, -2, -27, 12, 17, 3, -48, 40, 40, 127, 11, 
  7, -14, -110, 35, -49, 5, 3, -11, -20, -74, -18, -13, -56, 97, -127, 124, -9, -40, -18, -11, 
  53, -60, -107, 127, 45, -13, 61, 34, -127, -103, 36, -39, -127, -127, -32, -7, -72, -127, -56, -127, 
  127, 24, -67, -4, -14, -19, 9, -66, 33, -11, -103, 127, -127, -85, 17, 26, -105, -121, -43, 127, 
  46, 32, -65, 41, -61, 20, -41, 105, -95, 70, -45, -127, -106, 85, -49, -72
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_1_bias[] = {
  469, 1727, 643, -38, 357, -174, 282, 1510, -12, 7, 93, 48, 63, 181, 245, 143, -148, 443, 7, 32, 
  198, 876, -126, -439, 448, 346, 723, -19, 20, 15, 92, 911, -235, -251, 161, 623, 283, 892, 870, 580, 
  -8, -80, -149, 360, 47, 265, 1284, 1494, -155, 162, 302, 2, 363, 170, -70, 68, 174, 346, 8, 695, 
  528, 791, 390, -10
};
#else
static NS_PUT_IN_TCM int32_t *dw_1_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_1_scratch_buffer[SCRATCH_BUFFER_SIZE];
alignas(16) static NS_PUT_IN_TCM int8_t dw_1_weight_sum_buffer[WEIGHT_SUM_BUFFER_SIZE];


static cmsis_nn_context dw_1_ctx = {
    .buf = dw_1_scratch_buffer,
    .size = sizeof(dw_1_scratch_buffer),
};

static cmsis_nn_context dw_1_weight_sum_ctx = {
    .buf = dw_1_weight_sum_buffer,
    .size = sizeof(dw_1_weight_sum_buffer),
};


const cmsis_nn_per_channel_quant_params dw_1_quant_params = {
    .multiplier = (int32_t*)dw_1_multiplier,
    .shift = (int32_t*)dw_1_shift,
};

const cmsis_nn_dw_conv_params dw_1_dw_conv_params = {
    .input_offset = -dw_1_input_zero_point,
    .output_offset = dw_1_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_1_init(void)
{
    return arm_depthwise_convolve_weight_sum(
        (int32_t *)dw_1_weight_sum_buffer,
        NULL, // No scratch buffer required
        dw_1_weights,
        &dw_1_dw_conv_params,
        &dw_1_input_dims,
        &dw_1_filter_dims,
        &dw_1_output_dims,
        dw_1_dw_conv_params.input_offset,
        dw_1_bias
    );
}


int32_t aot_depthwise_conv_1_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_1_ctx,
        &dw_1_weight_sum_ctx,
        &dw_1_dw_conv_params,
        &dw_1_quant_params,
        &dw_1_input_dims,
        input,
        &dw_1_filter_dims,
        dw_1_weights,
        &dw_1_bias_dims,
        dw_1_bias,
        &dw_1_output_dims,
        output
    );

}
