/******************************************************************************
 * @file        aot_average_pool_27.c
 * @brief       Autogenerated AOT AVERAGE_POOL_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #27 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_average_pool_27.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 0
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 1024
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims pool_27_input_dims = { .n = 1, .h = 3, .w = 3, .c = 256 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, 1].
static const cmsis_nn_dims pool_27_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 1 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT]. C_OUT = C_IN
static const cmsis_nn_dims pool_27_output_dims = { .n = 1, .h = 1, .w = 1, .c = 256 };

alignas(16) static NS_PUT_IN_TCM int8_t pool_27_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context pool_27_context = {
    .buf = pool_27_scratch_buffer,
    .size = sizeof(pool_27_scratch_buffer),
};

const cmsis_nn_pool_params pool_27_average_pool_params = {
    .stride.w = 3,
    .stride.h = 3,
    .padding.w = 0,
    .padding.h = 0,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
aot_average_pool_27_init(void)
{
    return 0;
}


int32_t
aot_average_pool_27_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_avgpool_s8(
        &pool_27_context,
        &pool_27_average_pool_params,
        &pool_27_input_dims,
        input,
        &pool_27_filter_dims,
        &pool_27_output_dims,
        output
    );

}
