/******************************************************************************
 * @file        aot_model.c
 * @brief       Autogenerated HeliosAOT test case
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-03.
 *   This file is used to verify the correctness of the generated AOT C module.
 *
 * @date        2025-06-03
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdint.h>
#include <stdlib.h>
#include <math.h>
#include "ns_ambiqsuite_harness.h"
#include "aot_model.h"
#include "aot_test_case.h"

static int8_t aot_test_stimulus_input_0[192] = {
  44, 14, 19, 123, 121, 95, 25, 104, 115, 70, 40, 51, 106, 49, 99, 29, 82, 9, 73, 114, 
  90, 47, 79, 38, 85, 103, 96, 24, 98, 81, 124, 1, 123, 95, 18, 54, 98, 78, 0, 2, 
  61, 92, 125, 11, 35, 8, 77, 5, 105, 102, 103, 77, 126, 118, 85, 17, 46, 113, 54, 7, 
  87, 103, 105, 50, 107, 82, 21, 82, 33, 39, 14, 38, 100, 70, 70, 85, 122, 63, 34, 73, 
  111, 2, 117, 57, 83, 64, 23, 113, 48, 17, 90, 64, 58, 79, 73, 103, 99, 83, 99, 0, 
  41, 123, 23, 4, 98, 116, 6, 34, 116, 114, 116, 62, 52, 116, 100, 44, 67, 55, 90, 50, 
  61, 63, 54, 19, 13, 123, 67, 86, 51, 29, 83, 53, 73, 76, 25, 46, 77, 39, 111, 72, 
  78, 4, 54, 15, 68, 85, 77, 98, 101, 103, 114, 63, 83, 76, 89, 72, 102, 56, 109, 0, 
  14, 56, 97, 77, 25, 30, 48, 7, 12, 110, 5, 42, 113, 22, 71, 98, 83, 87, 95, 46, 
  104, 47, 26, 20, 68, 121, 124, 105, 107, 110, 23, 27
};
static int8_t aot_test_stimulus_output_0[27];
static int8_t aot_test_stimulus_golden_0[27] = {
  124, 1, 123, 98, 78, 0, 125, 11, 35, 34, 73, 111, 83, 64, 23, 90, 64, 58, 67, 86, 
  51, 73, 76, 25, 111, 72, 78
};
static int8_t aot_test_stimulus_output_1[48];
static int8_t aot_test_stimulus_golden_1[48] = {
  113, 54, 7, 87, 103, 105, 50, 107, 82, 21, 82, 33, 2, 117, 57, 83, 64, 23, 113, 48, 
  17, 90, 64, 58, 116, 6, 34, 116, 114, 116, 62, 52, 116, 100, 44, 67, 29, 83, 53, 73, 
  76, 25, 46, 77, 39, 111, 72, 78
};
static int8_t aot_test_stimulus_output_2[36];
static int8_t aot_test_stimulus_golden_2[36] = {
  44, 14, 19, 70, 40, 51, 73, 114, 90, 105, 102, 103, 113, 54, 7, 21, 82, 33, 99, 83, 
  99, 116, 6, 34, 100, 44, 67, 68, 85, 77, 76, 89, 72, 97, 77, 25
};
static int8_t aot_test_stimulus_output_3[192];
static int8_t aot_test_stimulus_golden_3[192] = {
  47, 79, 38, 73, 114, 90, 29, 82, 9, 106, 49, 99, 70, 40, 51, 25, 104, 115, 123, 121, 
  95, 44, 14, 19, 8, 77, 5, 125, 11, 35, 2, 61, 92, 98, 78, 0, 95, 18, 54, 124, 
  1, 123, 24, 98, 81, 85, 103, 96, 39, 14, 38, 21, 82, 33, 50, 107, 82, 87, 103, 105, 
  113, 54, 7, 85, 17, 46, 77, 126, 118, 105, 102, 103, 79, 73, 103, 90, 64, 58, 113, 48, 
  17, 83, 64, 23, 2, 117, 57, 34, 73, 111, 85, 122, 63, 100, 70, 70, 55, 90, 50, 100, 
  44, 67, 62, 52, 116, 116, 114, 116, 116, 6, 34, 23, 4, 98, 0, 41, 123, 99, 83, 99, 
  4, 54, 15, 111, 72, 78, 46, 77, 39, 73, 76, 25, 29, 83, 53, 67, 86, 51, 19, 13, 
  123, 61, 63, 54, 30, 48, 7, 97, 77, 25, 0, 14, 56, 102, 56, 109, 76, 89, 72, 114, 
  63, 83, 98, 101, 103, 68, 85, 77, 110, 23, 27, 124, 105, 107, 20, 68, 121, 104, 47, 26, 
  87, 95, 46, 71, 98, 83, 42, 113, 22, 12, 110, 5
};

static const void *aot_test_stimulus_golden[] = {
    aot_test_stimulus_golden_0,
    aot_test_stimulus_golden_1,
    aot_test_stimulus_golden_2,
    aot_test_stimulus_golden_3
};



static void aot_test_stimulus_callback(
    int32_t op,
    aot_operator_state_e state,
    int32_t status,
    void *user_data
) {
    if (state == aot_model_state_finished) {
        ns_lp_printf("Operation %d finished with status %d\n", op, status);
    }
}

aot_model_context_t aot_test_stimulus_context = {
    .input_data = {
       aot_test_stimulus_input_0
    },
    .output_data = {
       aot_test_stimulus_output_0, aot_test_stimulus_output_1, aot_test_stimulus_output_2, aot_test_stimulus_output_3
    },
    .callback = aot_test_stimulus_callback,
    .user_data = NULL
};

int32_t aot_test_case_init(void)
{
    return aot_model_init(&aot_test_stimulus_context);
}

int32_t aot_test_case_run(void)
{
    int32_t result = 0;

    result = aot_model_run(&aot_test_stimulus_context);
    if (result != 0) {
        ns_lp_printf("Model run failed with status %d\n", result);
        return result;
    }

    for (int j = 0; j < aot_outputs_len[0]; j++) {
        float act = aot_test_stimulus_output_0[j];
        float exp = aot_test_stimulus_golden_0[j];
        float diff = fabs(act - exp);
        if (diff > 1.0) {
            ns_lp_printf("Output mismatch at index [0][%d]: expected %f, got %f\n", j, exp, act);
            result = 1;
        }
    }

    for (int j = 0; j < aot_outputs_len[1]; j++) {
        float act = aot_test_stimulus_output_1[j];
        float exp = aot_test_stimulus_golden_1[j];
        float diff = fabs(act - exp);
        if (diff > 1.0) {
            ns_lp_printf("Output mismatch at index [1][%d]: expected %f, got %f\n", j, exp, act);
            result = 1;
        }
    }

    for (int j = 0; j < aot_outputs_len[2]; j++) {
        float act = aot_test_stimulus_output_2[j];
        float exp = aot_test_stimulus_golden_2[j];
        float diff = fabs(act - exp);
        if (diff > 1.0) {
            ns_lp_printf("Output mismatch at index [2][%d]: expected %f, got %f\n", j, exp, act);
            result = 1;
        }
    }

    for (int j = 0; j < aot_outputs_len[3]; j++) {
        float act = aot_test_stimulus_output_3[j];
        float exp = aot_test_stimulus_golden_3[j];
        float diff = fabs(act - exp);
        if (diff > 1.0) {
            ns_lp_printf("Output mismatch at index [3][%d]: expected %f, got %f\n", j, exp, act);
            result = 1;
        }
    }


    if (result == 0) {
        ns_lp_printf("Test passed!\n");
    } else {
        ns_lp_printf("Test failed!\n");
    }
    return result;

}
