/******************************************************************************
 * @file        aot_depthwise_conv_9.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #9 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_9.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_9_input_dims = { .n = 1, .h = 12, .w = 12, .c = 64 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_9_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 64 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_9_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 64 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_9_output_dims = { .n = 1, .h = 12, .w = 12, .c = 64 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_9_multiplier[64] = {
  1243458175, 1700278421, 2046320159, 1388655650, 1126270643, 1799349941, 1239030393, 2064818134, 1440647447, 1613207706, 1305052744, 1987673645, 1439088061, 1366393262, 1482048890, 1196037649, 1085912379, 1794458510, 1226099630, 1347422139, 
  1116649633, 2075305652, 1517941885, 1075749327, 1634031274, 1937785050, 1430059626, 1868696104, 1322997912, 1427049768, 1541525946, 1418904433, 1581480717, 1145554580, 1418551218, 1890815382, 1367193029, 1531560714, 2138685417, 1523424624, 
  1713909661, 2077860220, 1648436445, 1991308625, 1244770350, 2141522784, 1317219835, 1624073515, 1526873056, 1531298305, 2103530132, 1110912210, 1135971945, 1129151196, 1655056588, 1238788374, 1973082304, 1316012777, 1958985768, 1160699235, 
  2054832766, 1202874102, 1620144843, 1120360348
};
static const int32_t dw_9_shift[64] = {
  -5, -7, -7, -7, -5, -6, -6, -8, -7, -6, -6, -7, -7, -6, -6, -6, -6, -8, -6, -6, 
  -6, -7, -6, -6, -7, -7, -7, -7, -7, -6, -8, -7, -7, -6, -7, -6, -6, -6, -7, -6, 
  -7, -7, -7, -8, -7, -8, -6, -8, -7, -7, -7, -6, -6, -6, -7, -6, -7, -6, -7, -6, 
  -7, -6, -6, -6
};

// Offsets and activation parameters.
static const int32_t dw_9_input_zero_point = -128;
static const int32_t dw_9_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_9_weights[] = {
  -78, -105, 18, -106, -116, 19, -35, 84, -77, 10, -77, 17, -7, 56, -53, -16, -37, 73, 62, 15, 
  -96, -106, 54, 58, 107, 59, 86, -53, -37, -60, 10, -3, 19, -108, -16, 17, 28, -102, -2, 41, 
  -46, -68, -58, -4, 7, -23, 76, 8, 127, -102, 83, 24, 16, -62, -98, -74, 127, 124, -73, 55, 
  107, -53, -19, -50, 93, -9, -122, 20, -127, 82, 90, -14, 95, -95, -50, -37, 45, -2, -91, 44, 
  -60, 66, 121, -90, 127, 38, 14, -81, -102, -114, 39, -127, -72, -109, 25, -11, -15, -127, 117, -93, 
  -127, 103, 23, -16, -31, 109, -123, 102, 27, -17, 22, 59, -24, 102, 101, 3, 57, -116, -127, -92, 
  -28, 127, -28, 77, -28, -80, -22, -28, -51, -30, -18, 108, -83, -40, 127, -122, 50, 1, 48, -51, 
  16, -48, -70, -26, -37, -74, -31, 47, 72, 127, 72, -21, -54, 15, 81, -89, -80, -35, 22, -44, 
  -53, -64, 0, -25, -7, -111, 22, -127, -15, -73, -78, 56, -58, -26, -38, 46, -31, 23, 13, -38, 
  14, -127, -92, -75, -45, 84, -95, -91, -41, -15, -2, 127, -25, 94, 85, -9, 4, -127, -86, 127, 
  -42, -124, 43, 90, 43, 126, 15, -72, 3, 105, 58, 2, -108, -57, -96, 36, -43, -13, 73, 21, 
  -59, 6, 121, 61, 127, 55, -73, 127, -127, -30, 56, 82, -21, -69, 31, 123, 97, -91, 127, 46, 
  93, -102, -38, 105, 12, 19, -8, -66, 15, -61, -85, 85, 127, -23, -36, -56, 127, 126, -18, 105, 
  107, 20, 22, 74, 127, -32, 127, 127, 127, -8, 127, 127, 50, 90, -7, -110, 43, 100, -127, -127, 
  127, -84, 127, 124, -63, 32, 18, 13, -38, 92, 100, 22, -4, 127, 127, 24, -38, 127, 116, 127, 
  127, -127, 32, 127, 64, -29, 25, 10, 118, -54, -51, 24, 20, -44, -20, 81, -62, -30, -20, 58, 
  -65, 12, -85, 106, 53, 94, 34, 92, 10, 127, -64, 30, 9, -127, 47, 55, 47, -17, -78, 73, 
  102, 25, 9, 37, -117, 127, 64, -93, -83, 9, 2, -115, -58, -58, -52, 14, 76, -21, 51, -102, 
  -19, -79, 40, 50, -63, -58, -76, 1, -68, 127, -127, -86, 11, -32, 13, 127, 24, -57, -127, -127, 
  -75, -106, 2, 54, -12, 127, 5, -86, 53, -67, -82, 72, -5, -104, 57, 81, 40, 52, -6, -12, 
  19, 127, -127, 26, -36, 59, -76, -33, -56, -120, -10, -41, -127, 35, 127, 127, 18, -37, -112, 71, 
  -67, 4, 19, 11, -19, -94, 58, -14, 27, -76, -15, 33, -100, 5, -53, 88, -88, 23, -99, -42, 
  -24, -50, 63, 40, 52, 36, -29, -16, 7, 104, 19, 68, 112, -46, -46, 38, 83, 43, -62, -6, 
  119, 5, -10, -67, 127, 44, -96, -127, -61, -12, -42, -63, 44, 34, -56, 45, -98, 127, 103, 7, 
  -87, 17, -33, -5, 106, 38, 86, 31, -127, 35, 127, 3, 20, -60, -77, 50, 2, -113, -91, 9, 
  -127, -22, -78, 25, 41, -61, 82, -18, -25, 127, -69, -86, 1, -112, -127, 127, 9, 75, -126, -11, 
  -15, 82, 12, 6, -66, -77, -47, 17, 9, 80, -6, 15, -14, -17, 87, -23, -50, 105, -50, -105, 
  -52, 5, -10, -118, -25, -39, -127, -33, 30, -14, 12, 59, -54, -2, 40, 27, 12, 7, -55, 9, 
  -19, -41, 20, -127, -55, 8, -56, 110, 20, -40, 65, -85, -30, 22, 127, -28
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_9_bias[] = {
  -230, -3345, 3352, -4400, -423, -932, -325, -5482, -3116, 1589, -667, -2888, -6702, -201, 840, -1033, -710, -6680, 910, 3329, 
  -1762, -2358, 2758, 4281, -125, -1928, -3800, 4100, 11712, 371, -5756, 1008, -191, 3458, 4092, -1283, 779, -1433, -6402, -475, 
  6984, -75, -1175, -6046, -4662, 7947, -1348, -3567, 18, 346, -220, -220, 770, 3828, 4184, -389, -2191, -889, 3340, -1526, 
  -722, 627, 61, 2658
};
#else
static NS_PUT_IN_TCM int32_t *dw_9_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_9_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context dw_9_context = {
    .buf = dw_9_scratch_buffer,
    .size = sizeof(dw_9_scratch_buffer),
};


int32_t aot_depthwise_conv_9_init(void)
{
    return 0;
}

const cmsis_nn_per_channel_quant_params dw_9_quant_params = {
    .multiplier = (int32_t*)dw_9_multiplier,
    .shift = (int32_t*)dw_9_shift,
};

const cmsis_nn_dw_conv_params dw_9_dw_conv_params = {
    .input_offset = -dw_9_input_zero_point,
    .output_offset = dw_9_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_9_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_9_context,
        &dw_9_dw_conv_params,
        &dw_9_quant_params,
        &dw_9_input_dims,
        input,
        &dw_9_filter_dims,
        dw_9_weights,
        &dw_9_bias_dims,
        dw_9_bias,
        &dw_9_output_dims,
        output
    );

}
