/******************************************************************************
 * @file        aot_depthwise_conv_3.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   This kernel represents node #3 in the corresponding graph.
 *
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_3.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#define WEIGHT_SUM_BUFFER_SIZE 256
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_3_input_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_3_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 64 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_3_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 64 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_3_output_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_3_multiplier[64] = {
  1714133752, 1698805621, 1693693347, 1216969937, 1735814305, 1879620052, 1554176332, 1477316785, 1624124963, 1738267546, 1951688197, 1963805900, 1856832425, 1796474680, 1162897160, 1139020700, 2040819946, 2076564242, 1735670948, 1418463255, 
  1231094892, 1214681724, 1867559032, 1754692957, 2044652774, 1231630617, 2044833104, 1525740462, 1851553165, 1106654797, 1428586437, 1724402251, 1087753987, 1823558753, 1714680984, 1468675047, 1284410604, 1423009689, 2053024691, 1324499214, 
  1147243383, 1361934788, 2122974424, 1098402732, 1640228278, 1203990620, 1420131027, 1685960602, 1863302374, 1544851228, 1476837620, 1731253058, 1080317016, 1798928655, 1508177126, 1882108061, 1282398210, 1240758620, 1290956455, 1958000465, 
  1951353125, 1928126488, 1748347635, 1966609638
};
static const int32_t dw_3_shift[64] = {
  -7, -7, -6, -6, -7, -6, -7, -7, -6, -7, -7, -7, -7, -7, -6, -6, -7, -7, -7, -7, 
  -7, -5, -7, -7, -7, -6, -7, -7, -7, -6, -7, -7, -5, -7, -7, -6, -7, -7, -7, -7, 
  -6, -6, -7, -7, -7, -6, -6, -7, -7, -7, -6, -6, -6, -7, -7, -7, -6, -6, -6, -7, 
  -7, -7, -7, -7
};

// Offsets and activation parameters.
static const int32_t dw_3_input_zero_point = -128;
static const int32_t dw_3_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_3_weights[] = {
  88, -73, -67, 63, -52, -33, -3, 118, 8, -103, 78, 55, -26, 80, 127, -94, 18, 96, 127, -52, 
  102, -11, 79, -16, 3, -11, 76, 15, 111, -45, -81, -22, 9, 85, -127, 29, 3, 41, 79, 127, 
  -28, -4, -69, 114, -36, 44, 37, 85, -7, 100, 53, 8, -42, 10, -92, -60, 45, 72, -127, -52, 
  11, -28, 22, -50, -1, -59, 11, -69, -91, 14, 29, -66, 43, -72, 42, 84, -39, 127, -43, 127, 
  102, 30, 40, 11, 116, -34, -25, 77, 127, -5, -115, -90, -48, -23, -47, 127, 52, -104, 113, -4, 
  -36, -57, 127, 2, -69, -127, -47, 64, -33, 97, -86, -11, 66, -44, -16, 83, -123, -19, -27, -32, 
  -4, -28, -19, -11, -22, -39, 14, -127, 38, -42, 127, 71, 125, 28, -69, 119, 2, 11, 104, -41, 
  127, -13, 4, -33, 18, 127, -43, -15, -87, -127, 112, -57, 69, -34, -48, 26, -48, -69, -41, -1, 
  -72, 4, -115, 49, 25, -21, -28, 34, -111, -14, -37, -74, -76, -71, 6, -21, -127, -22, -127, -23, 
  -32, -55, -31, 127, -31, -17, 21, -10, 0, 60, -21, -85, 127, 20, -72, 52, -111, -60, 32, 108, 
  28, -60, 15, 58, -109, 74, 80, -50, -56, 89, 117, -72, 84, -4, 91, -23, -93, 24, 106, 51, 
  127, 127, -119, -34, 37, 57, -73, -1, -72, 127, -12, -7, 50, -5, -31, 64, -101, -42, 83, 127, 
  124, 109, -1, -21, -127, -61, -105, -21, 52, 76, -11, -11, 59, -99, -12, -18, 9, -67, 18, 14, 
  28, -34, 58, 19, 11, -58, 58, -24, -9, 121, -119, 44, 127, 44, -47, -38, 127, -26, 20, 50, 
  90, -4, -49, 72, -52, 14, -9, 47, 65, -25, 53, -34, -84, -44, 57, 120, 31, 52, -51, -5, 
  -66, 71, -6, -41, 34, -16, -89, 38, -65, 0, 53, 35, 56, 3, -36, -30, -48, -72, 127, -79, 
  -12, -51, 45, 8, 127, -25, 2, -112, -17, 57, 84, -29, 62, 18, 120, -39, -35, 58, -20, -61, 
  -49, -20, -23, -93, 64, 37, -127, 110, 43, 41, 122, -34, 11, -58, -38, 93, -57, -40, -98, -56, 
  -21, -38, -28, -121, -90, 28, 3, 15, -121, -7, -24, 46, 50, -127, -83, 43, 40, -105, 55, -102, 
  68, 15, -79, -102, 97, 64, -24, 127, -6, -40, 127, 33, 127, -127, -67, 108, -91, 35, -51, 36, 
  -25, 44, 64, -127, -9, -46, 109, -127, -125, 87, 108, 58, 86, 63, -127, -43, 31, 22, -110, -46, 
  -101, 94, 72, -18, 60, -19, -28, 127, -127, -56, 127, 22, 85, 127, -104, -127, -31, -107, -32, -90, 
  127, 6, 72, -85, 77, -15, -21, 71, 47, -127, -43, -15, 64, -12, 22, -36, -28, -21, 43, -127, 
  23, 66, 24, 18, 83, 36, 55, -108, -7, -9, -31, -12, 95, 23, 87, 82, 11, 51, -20, 15, 
  127, 79, 14, -54, -60, -93, 125, 76, 94, 100, -127, -13, -72, -17, -6, 16, 22, -12, 7, -9, 
  -34, -60, 36, 34, 100, 36, -51, -88, 36, -21, 96, 11, 50, -60, -3, 55, 1, -127, -41, -127, 
  -2, 88, 127, 29, 31, 82, 126, -45, -47, 81, 22, -87, -102, -17, -127, -49, 78, 127, -98, 127, 
  92, 121, 83, -74, 33, -127, 35, 127, -127, -7, -2, -57, 127, 66, -35, -68, -13, 127, -92, -3, 
  -62, -32, 88, 41, -66, -96, -127, 47, 25, -127, 110, -127, 127, -127, -55, -20
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_3_bias[] = {
  -2035, 2513, 217, -1406, -679, 1521, -728, 13, -1061, 2147, -1582, -878, 614, -2680, -1258, 305, -836, -2719, -1724, 3249, 
  -661, 1390, -1287, 1092, -1899, -1060, 955, -1120, -1365, -1494, 2366, -25, -1129, 285, 1159, -954, 3192, 30, -1114, -1311, 
  -860, -177, 2280, -1374, 3264, -944, -335, -732, -897, -1152, 1702, -383, 2357, 2805, 2356, -497, -1255, 600, 255, 3030, 
  -1217, 1745, -604, 2423
};
#else
static NS_PUT_IN_TCM int32_t *dw_3_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_3_scratch_buffer[SCRATCH_BUFFER_SIZE];
alignas(16) static NS_PUT_IN_TCM int8_t dw_3_weight_sum_buffer[WEIGHT_SUM_BUFFER_SIZE];


static cmsis_nn_context dw_3_ctx = {
    .buf = dw_3_scratch_buffer,
    .size = sizeof(dw_3_scratch_buffer),
};

static cmsis_nn_context dw_3_weight_sum_ctx = {
    .buf = dw_3_weight_sum_buffer,
    .size = sizeof(dw_3_weight_sum_buffer),
};


const cmsis_nn_per_channel_quant_params dw_3_quant_params = {
    .multiplier = (int32_t*)dw_3_multiplier,
    .shift = (int32_t*)dw_3_shift,
};

const cmsis_nn_dw_conv_params dw_3_dw_conv_params = {
    .input_offset = -dw_3_input_zero_point,
    .output_offset = dw_3_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_3_init(void)
{
    return arm_depthwise_convolve_weight_sum(
        (int32_t *)dw_3_weight_sum_buffer,
        NULL, // No scratch buffer required
        dw_3_weights,
        &dw_3_dw_conv_params,
        &dw_3_input_dims,
        &dw_3_filter_dims,
        &dw_3_output_dims,
        dw_3_dw_conv_params.input_offset,
        dw_3_bias
    );
}


int32_t aot_depthwise_conv_3_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_3_ctx,
        &dw_3_weight_sum_ctx,
        &dw_3_dw_conv_params,
        &dw_3_quant_params,
        &dw_3_input_dims,
        input,
        &dw_3_filter_dims,
        dw_3_weights,
        &dw_3_bias_dims,
        dw_3_bias,
        &dw_3_output_dims,
        output
    );

}
