/******************************************************************************
 * @file        aot_conv_0.c
 * @brief       Autogenerated AOT CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-04.
 *   This kernel represents node #0 in the corresponding graph.
 *
 * @date        2025-06-04
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_conv_0.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 128
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 112
#else
#define SCRATCH_BUFFER_SIZE 112
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_0_input_dims = { .n = 1, .h = 96, .w = 96, .c = 3 };

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_0_filter_dims = { .n =  8, .h = 3, .w = 3, .c = 3 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_0_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 8 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_0_output_dims = { .n = 1, .h = 48, .w = 48, .c = 8 };

// Quantization parameters (per-channel quantization)
static const int32_t conv_0_multiplier[8] = {
  1179182720, 1673859840, 1629160064, 1965349120, 2002280832, 1493832064, 1343197952, 1089360000
};
static const int32_t conv_0_shift[8] = {
  -7, -8, -8, -8, -9, -10, -8, -9
};

// Offsets and activation parameters.
static const int32_t conv_0_input_zero_point = -128;
static const int32_t conv_0_output_zero_point = -128;

// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t conv_0_weights[] = {
  38, -93, 71, 34, -123, 102, -1, -127, 87, 3, -93, 87, -14, -42, 13, 21, 1, 41, 29, -20, 
  -5, 70, -97, 27, 47, -88, 1, -57, -31, 127, -96, -2, 42, -92, -21, 120, 8, -42, 17, -101, 
  5, 70, -51, 45, 16, 47, -15, -32, 58, -42, 29, 27, -15, -11, -80, -96, -76, -35, -80, -69, 
  12, 1, -36, 10, -80, -14, -11, -53, 22, 23, 22, 11, -12, 9, 25, 44, 12, 11, 127, 23, 
  37, 85, 39, -20, -37, -102, -77, 91, 28, -8, 50, 26, 36, -94, -72, -127, 48, -3, 4, 53, 
  -33, 28, -94, -5, 38, -6, 45, 26, -34, 47, 17, -71, 25, 35, -90, -28, 25, 29, 70, -68, 
  -50, -52, -37, -127, -41, -53, 15, 31, 33, 15, 77, -70, -62, -89, -72, -28, 73, -44, -91, -78, 
  -74, -59, -8, 9, 77, 106, 47, 21, -37, 58, -59, -89, -115, 58, 86, -22, 127, 58, 11, -3, 
  -19, 14, 69, -39, -18, 84, -49, -50, 27, -54, 33, 49, -57, -5, -5, -64, 54, 41, -60, 33, 
  28, -72, 37, 92, -127, 71, 79, -121, -15, 26, -3, -38, -72, 40, 73, -127, -2, -13, 18, 31, 
  11, 17, -18, -35, -96, -33, -72, 18, -17, 47, -29, 57, -44, -52, 44, -69
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t conv_0_bias[] = {
  12398, 12434, 33904, 18963, 50193, 77222, 15216, 89048
};
#else
static NS_PUT_IN_TCM int32_t *conv_0_bias = NULL;
#endif


alignas(16) static NS_PUT_IN_TCM int8_t conv_0_scratch_buffer[SCRATCH_BUFFER_SIZE];

static cmsis_nn_context conv_0_context = {
    .buf = conv_0_scratch_buffer,
    .size = sizeof(conv_0_scratch_buffer),
};

const cmsis_nn_per_channel_quant_params conv_0_quant_params = {
    .multiplier = (int32_t*)conv_0_multiplier,
    .shift = (int32_t*)conv_0_shift,
};


const cmsis_nn_conv_params conv_0_conv_params = {
    .input_offset = -conv_0_input_zero_point,
    .output_offset = conv_0_output_zero_point,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_conv_0_init(void)
{
    return 0;
}

int32_t aot_conv_0_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_convolve_wrapper_s8(
        &conv_0_context,
        &conv_0_conv_params,
        &conv_0_quant_params,
        &conv_0_input_dims,
        input,
        &conv_0_filter_dims,
        conv_0_weights,
        &conv_0_bias_dims,
        conv_0_bias,
        &conv_0_output_dims,
        output
    );

}
