/******************************************************************************
 * @file        aot_depthwise_conv_5.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   This kernel represents node #5 in the corresponding graph.
 *
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_depthwise_conv_5.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 4464
#define WEIGHT_SUM_BUFFER_SIZE 256
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#endif

#define HAS_BIAS 1

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_5_input_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_5_filter_dims = { .n = 1, .h = 3, .w = 3, .c = 64 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_5_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 64 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_5_output_dims = { .n = 1, .h = 25, .w = 5, .c = 64 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_5_multiplier[64] = {
  1175859562, 1325308050, 1807069200, 1420124271, 1188850090, 1182411826, 1831798253, 1649441596, 1897229520, 1960284024, 1088449917, 1672116795, 1343192385, 1487293887, 1672031270, 1674544455, 2061041943, 1951124498, 1660944822, 1092926841, 
  1362949302, 1686277765, 1889942367, 2094598643, 1884567220, 2137666356, 1554431692, 1602323645, 1300969388, 1742212516, 2087562224, 1697886333, 1743893709, 1139931211, 1408896915, 2007149259, 2008015774, 2115739605, 1364939324, 1669828999, 
  1224912049, 1117851976, 1283481598, 1789833187, 1167721435, 1534981936, 1382726870, 1907838383, 1372677674, 1120008250, 1414728578, 1400938390, 2122221780, 1317835141, 2026088264, 1627366011, 1688802527, 1657532372, 1082442094, 1658124163, 
  1837593306, 1539460112, 1223606748, 1717328997
};
static const int32_t dw_5_shift[64] = {
  -6, -7, -7, -7, -7, -6, -8, -7, -8, -7, -6, -7, -7, -7, -7, -7, -7, -7, -7, -7, 
  -7, -7, -8, -7, -8, -8, -7, -7, -6, -7, -8, -7, -7, -7, -7, -8, -7, -7, -7, -8, 
  -7, -7, -7, -8, -7, -7, -7, -7, -7, -6, -7, -6, -8, -7, -7, -7, -7, -7, -7, -7, 
  -7, -7, -6, -7
};

// Offsets and activation parameters.
static const int32_t dw_5_input_zero_point = -128;
static const int32_t dw_5_output_zero_point = -128;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_5_weights[] = {
  -127, 58, -17, -41, -127, -104, -93, -29, 127, 103, 17, -7, 114, 12, -80, -7, -78, -115, -34, -25, 
  9, 127, 62, -47, 60, -82, 97, 27, -16, 67, -86, -16, 127, -123, 127, -123, 127, 17, 76, -37, 
  24, -127, 127, 121, 57, 72, 127, 117, -62, 117, 53, 127, 127, 112, -78, 67, 44, -6, 96, -41, 
  34, 22, -45, -24, 37, 26, 127, 15, 55, -34, -116, -14, 48, 73, -56, -98, 40, 87, 62, -23, 
  -16, -43, -54, -13, -27, 26, 127, -42, 25, -105, -39, 127, 127, 55, -109, -19, 35, -127, 60, -9, 
  -88, 37, 67, 14, 82, -92, 90, 66, -127, 71, 16, -34, -94, -4, 5, 33, -8, -74, 105, 35, 
  -69, -42, 76, 25, 34, 31, -4, 59, 21, 67, -51, 83, -47, 127, -27, -127, 69, 127, 42, -44, 
  -71, 25, 61, -127, -127, 54, -115, -127, -53, 79, 40, 55, 10, -97, -127, -83, 36, 72, 9, 19, 
  -73, -88, 116, -93, 90, 58, -62, 32, -127, 14, 78, 127, 93, 4, 62, 85, 114, -60, -11, 39, 
  57, 34, 11, 53, -91, -9, -127, 127, 127, -127, -21, 54, 24, 127, -33, -87, -39, -8, -52, -35, 
  66, 34, 43, 47, 97, -36, -84, -3, -22, -7, -68, -93, 7, 70, 119, -2, -5, -64, -41, 77, 
  -45, 26, -43, 30, 89, -84, 90, -127, 55, -10, 106, 125, 24, -57, 74, 64, 47, 75, 70, 32, 
  -36, 59, 60, 29, 74, 87, 12, 74, -13, -50, 20, -19, -44, 58, 13, 60, 26, 17, 31, 45, 
  57, -20, 5, -47, 109, -23, -75, -60, 43, 42, -8, -123, 47, -62, -35, 26, -95, 11, -15, -55, 
  127, -69, -94, 75, 74, 47, 0, 33, 36, -46, 28, 21, -88, -5, 55, 107, 58, -94, 42, 76, 
  -51, 57, 2, -38, -41, -13, 5, 44, 1, 48, 41, -28, 49, -14, 95, -16, 70, -52, -17, 42, 
  77, -10, -19, 37, -119, 40, 82, -92, 76, 74, 87, -127, -60, 69, -76, -80, -23, 19, -127, -88, 
  -43, -18, 94, 44, 87, -19, -75, -21, 14, 101, 33, 54, -9, -1, 26, -87, 27, 44, -68, 56, 
  7, -79, 93, 75, -27, -87, 73, 45, 97, 28, 38, 23, 26, 48, -32, 69, -21, 3, -70, 82, 
  104, -91, -12, 53, 52, 75, -1, -99, -36, 49, -127, -90, 24, -96, -11, 39, 127, -127, -47, -75, 
  -33, -103, -53, -60, -72, -24, 80, 127, 21, -127, -55, 39, -42, 59, -127, 127, 23, -47, -41, -125, 
  17, 127, 91, 116, 89, -112, -56, 65, 115, 15, 9, -127, -92, 127, 83, 6, 80, 127, 35, 8, 
  -127, -127, 18, -94, -34, 66, -75, 127, 33, 74, 12, -5, 109, -32, -57, -24, 51, -25, -41, -97, 
  98, 37, -33, -25, 75, -35, -58, 122, -127, -22, -11, -51, 122, -39, 58, 62, 110, -5, -89, 57, 
  -29, -2, 1, 30, -13, 87, -7, 127, 95, 0, 30, -124, 15, 105, 10, 31, -127, 27, 3, 14, 
  93, 39, 53, -127, -46, -64, 62, -87, -6, -88, -67, 41, 7, 55, -83, 127, -123, 49, -96, 3, 
  7, 71, 127, 2, 53, 15, -127, 69, 3, -127, -94, 29, -21, 92, 63, 83, 42, -31, 18, 86, 
  -88, 127, -29, 0, 17, -21, 93, -82, -50, 55, -127, -74, -12, -95, -5, 42, 19, -127, 64, -95, 
  -20, -13, 127, -1, 106, 57, -127, 58, -1, -104, -46, -50, 5, -10, -127, 34
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t dw_5_bias[] = {
  -1333, -3619, -753, -1067, 2554, -120, 6201, 4230, -5422, -1668, -825, 3613, -4071, -617, 3491, 4556, 1795, 4054, 5848, 2363, 
  5193, -2022, -4199, -371, -4552, 6335, 2468, -3087, -1224, -3442, 5279, -2885, -2138, 5721, -3896, 7110, -174, -1711, -2261, -4003, 
  -2400, 5775, -3994, -4656, -1035, -1577, -3418, -559, 2939, -1270, -3062, -2249, -4745, -2934, -949, -2132, 2827, 4074, -1473, 1411, 
  -1383, 2562, 3340, -2837
};
#else
static NS_PUT_IN_TCM int32_t *dw_5_bias = NULL;
#endif

alignas(16) static NS_PUT_IN_TCM int8_t dw_5_scratch_buffer[SCRATCH_BUFFER_SIZE];
alignas(16) static NS_PUT_IN_TCM int8_t dw_5_weight_sum_buffer[WEIGHT_SUM_BUFFER_SIZE];


static cmsis_nn_context dw_5_ctx = {
    .buf = dw_5_scratch_buffer,
    .size = sizeof(dw_5_scratch_buffer),
};

static cmsis_nn_context dw_5_weight_sum_ctx = {
    .buf = dw_5_weight_sum_buffer,
    .size = sizeof(dw_5_weight_sum_buffer),
};


const cmsis_nn_per_channel_quant_params dw_5_quant_params = {
    .multiplier = (int32_t*)dw_5_multiplier,
    .shift = (int32_t*)dw_5_shift,
};

const cmsis_nn_dw_conv_params dw_5_dw_conv_params = {
    .input_offset = -dw_5_input_zero_point,
    .output_offset = dw_5_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t aot_depthwise_conv_5_init(void)
{
    return arm_depthwise_convolve_weight_sum(
        (int32_t *)dw_5_weight_sum_buffer,
        NULL, // No scratch buffer required
        dw_5_weights,
        &dw_5_dw_conv_params,
        &dw_5_input_dims,
        &dw_5_filter_dims,
        &dw_5_output_dims,
        dw_5_dw_conv_params.input_offset,
        dw_5_bias
    );
}


int32_t aot_depthwise_conv_5_run(const int8_t* __restrict input, int8_t* __restrict output)
{

    return arm_depthwise_conv_wrapper_s8(
        &dw_5_ctx,
        &dw_5_weight_sum_ctx,
        &dw_5_dw_conv_params,
        &dw_5_quant_params,
        &dw_5_input_dims,
        input,
        &dw_5_filter_dims,
        dw_5_weights,
        &dw_5_bias_dims,
        dw_5_bias,
        &dw_5_output_dims,
        output
    );

}
