/******************************************************************************
 * @file        aot_fully_connected_11.c
 * @brief       Autogenerated AOT FULLY_CONNECTED kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-06-10.
 *   This kernel represents node #11 in the corresponding graph.
 *
 * @date        2025-06-10
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "aot_fully_connected_11.h"

#define HAS_BIAS 1
#define IS_PER_CHANNEL_QUANTIZATION (0)

// Input dimensions: input shape is [N, H, W, C_IN]
static const cmsis_nn_dims fc_11_input_dims = { .n = 1, .h = 1, .w = 1, .c = 64 };

// Filter dimensions: weights shape is [(H * W * C_IN), 1, 1, C_OUT].
static const cmsis_nn_dims fc_11_filter_dims = { .n = 64, .h = 1, .w = 1, .c = 12 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims fc_11_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 12 };

// Output dimensions: output shape is [N, 1, 1, C_OUT].
static const cmsis_nn_dims fc_11_output_dims = { .n = 1, .h = 1, .w = 1, .c = 12 };

// Quantization parameters (per-channel quantization)
static const int32_t fc_11_multiplier[] = {
  1278221440
};
static const int32_t fc_11_shift[] = {
  -7
};

// Offsets and activation parameters.
static const int32_t fc_11_input_zero_point = -128;
static const int32_t fc_11_filter_zero_point = 0;
static const int32_t fc_11_output_zero_point = 14;

// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t fc_11_weights[] = {
  -80, -38, -39, 43, 6, 5, -15, 35, -6, 40, -71, 66, -30, -41, 37, 37, -69, -36, -70, 19, 
  23, -11, -80, -38, -49, 21, -86, 16, -16, 52, 87, -25, 10, -23, 35, -9, -7, 36, -28, -81, 
  -46, -41, 7, -92, -10, 84, 43, -67, -89, -29, 47, -44, 80, -74, -72, -41, -76, 23, 44, -30, 
  60, -20, -33, 32, 12, 65, -30, -38, 36, -18, 16, -42, 63, -57, 30, -13, 26, -51, 29, -16, 
  -68, -67, -47, 32, 48, -66, 3, -25, -82, -14, -72, -19, -31, -35, 26, -80, -83, 59, -45, 32, 
  -43, 13, 20, 56, -41, 54, -20, -70, 46, -5, 43, -46, 10, -35, -64, -37, -40, -21, -53, -17, 
  -36, 56, 69, -38, 29, -79, 26, 25, 54, -35, 25, -52, 14, -32, 35, -66, -47, -10, -14, -57, 
  56, 33, -73, -63, 76, 57, 51, -75, 24, 61, 60, 10, 62, -18, -61, -39, 9, -70, 9, -33, 
  42, 44, -50, -9, 13, -10, -57, 29, 26, -85, -42, -56, -61, -11, -68, -19, -79, 69, -29, -44, 
  -56, 8, 29, -4, -59, -83, -67, 35, -50, 68, -59, -17, -25, 31, -46, -55, 52, -38, -60, 19, 
  12, -10, -44, -52, 55, 4, -47, -21, -68, 53, -22, 2, 45, -46, -40, 58, -67, -65, -54, -56, 
  22, -49, -32, -53, -39, 51, 48, -52, 61, 39, -33, -9, -38, -65, -87, -50, 70, -30, 57, -19, 
  -12, -3, 16, -36, -31, -34, -46, -12, -28, 54, -30, 42, -53, -10, -28, 61, 12, -32, -62, -19, 
  67, 67, 59, -32, 22, -54, -81, -68, -4, 32, 10, -44, 24, -67, 20, 36, -69, 65, 44, 68, 
  60, 9, -74, -47, -97, 65, -38, -77, -74, 21, -8, -36, -47, -70, 9, -44, -41, -35, -54, 5, 
  -70, 11, -8, -36, -31, -75, -78, 40, -14, 46, 37, 27, 66, -27, -61, -40, -42, 0, 10, -81, 
  -94, 16, -23, 79, -65, 52, 45, 45, -28, -76, 8, 66, -38, 43, 5, -24, -54, -76, -47, 70, 
  -77, -88, 62, 63, -15, 70, -53, 39, -29, 19, -25, 45, 2, -63, -18, -67, -62, 33, 19, -71, 
  -75, 42, -26, 60, -58, 28, -25, 21, -49, -78, -79, 36, 69, 32, -81, -71, 40, -63, -3, -36, 
  26, -91, -28, -39, 60, -41, 56, -22, -41, -77, 55, -27, -2, -9, 73, -44, -50, 30, 73, -14, 
  -16, 60, 26, 36, -29, -20, -50, -63, 43, -12, 52, -25, 65, -54, -24, 3, 51, 43, -29, -49, 
  -36, 68, -61, 61, -34, -58, -4, 30, -67, -75, -59, -11, -28, 62, 24, -22, -85, -58, -63, 26, 
  -24, -60, -51, -28, 1, -54, 27, -58, -53, 50, -23, -59, 78, -11, -45, 72, -47, 87, -95, 41, 
  -31, -10, -29, -9, -45, 7, 85, -117, -56, -21, -57, -80, -37, -100, -55, -25, -54, 57, 24, -65, 
  18, -40, -64, 71, -64, -59, 79, 57, 65, 56, -36, 43, -37, 34, -42, 22, -4, -11, -85, -28, 
  -14, -5, -47, 58, 35, -34, -14, -26, 41, 23, -60, -97, -31, -15, -1, -35, -89, 40, 0, -82, 
  -42, -61, -25, -89, -51, 61, -79, -10, -72, -55, 56, -32, -88, 49, 24, -39, -13, -32, -3, -31, 
  -48, 46, -44, -2, -50, -58, -30, 45, -59, -50, -33, 36, 49, -31, -11, -65, -2, -6, 52, 67, 
  52, 24, -56, 60, 8, 56, -5, -77, 46, -12, 3, -1, 33, 9, 17, -27, -32, -84, -82, -7, 
  13, -28, -29, -82, -57, 59, -28, -31, 74, -44, -46, -42, 29, -11, -12, -72, 74, 42, 32, 51, 
  -20, -52, 3, 14, 37, -15, -25, -42, -47, -5, -52, -94, 70, -84, 81, -13, 8, -39, 61, -8, 
  -69, -31, -109, -56, 3, -60, 76, -79, -51, 29, 67, -8, 54, -67, -49, 42, -68, 30, -21, 64, 
  42, -43, 79, -81, -64, -76, -92, -69, 56, 39, -2, -79, -74, -36, 40, -90, -61, -69, -29, 1, 
  52, -52, 19, -44, 44, -58, 4, -26, 66, 1, -90, 35, -62, -85, -104, -70, -114, -25, -70, -31, 
  -61, -35, 66, -50, -14, 14, -53, -39, -49, -45, -65, -16, 60, -23, 65, -25, 65, -73, -56, -114, 
  -36, 50, -92, -127, -12, -44, 40, 55, 5, 10, 9, 31, 51, -38, 25, 47, -35, -28, -6, 61, 
  40, 5, -51, -15, 15, -45, 3, 6, 44, 61, 69, 69, 2, 10, -23, 72, 34, -4, 61, 24, 
  -5, -19, -55, -40, 38, 53, 58, 41, -13, -43, -18, 24, 39, -27, 21, -43, -4, -21, 20, 70, 
  -37, 8, 20, 64, -36, -38, 60, 2
};

#if HAS_BIAS
alignas(16) static NS_PUT_IN_TCM int32_t fc_11_bias[] = {
  -78, -16, -66, -88, -8, -92, -202, 32, -63, -151, -43, 171
};
#else
static NS_PUT_IN_TCM int32_t *fc_11_bias = NULL;
#endif


alignas(16) static NS_PUT_IN_TCM int32_t fc_11_kernel_sum[12];

static cmsis_nn_context fc_11_ctx = {
    .buf = (void *)fc_11_kernel_sum,
    .size = sizeof(fc_11_kernel_sum),
};

static cmsis_nn_fc_params fc_11_fc_params = {
    .input_offset = -fc_11_input_zero_point,
    .filter_offset = -fc_11_filter_zero_point,
    .output_offset = fc_11_output_zero_point,
    .activation.min = -128,
    .activation.max = 127,
};

#if IS_PER_CHANNEL_QUANTIZATION

const cmsis_nn_per_channel_quant_params fc_11_quant_params = {
    .multiplier = (int32_t*)fc_11_multiplier,
    .shift = (int32_t*)fc_11_shift,
};

#else

const cmsis_nn_per_tensor_quant_params fc_11_quant_params = {
    .multiplier = fc_11_multiplier[0],
    .shift = fc_11_shift[0],
};

#endif // IS_PER_CHANNEL_QUANTIZATION

int32_t aot_fully_connected_11_init(void)
{
    // Precompute kernel sums for each output channel.
    arm_vector_sum_s8(
        (int32_t *)fc_11_kernel_sum,
        fc_11_filter_dims.n,
        fc_11_filter_dims.c,
        fc_11_weights,
        fc_11_fc_params.input_offset,
        fc_11_fc_params.filter_offset,
        fc_11_bias
    );
    return 0;
}

int32_t aot_fully_connected_11_run(const int8_t* __restrict input, int8_t* __restrict output)
{

#if IS_PER_CHANNEL_QUANTIZATION

    return arm_fully_connected_per_channel_s8(
        &fc_11_ctx,
        &fc_11_fc_params,
        &fc_11_quant_params,
        &fc_11_input_dims,
        input,
        &fc_11_filter_dims,
        fc_11_weights,
        &fc_11_bias_dims,
        fc_11_bias,
        &fc_11_output_dims,
        output
    );

#else

    return arm_fully_connected_s8(
        &fc_11_ctx,
        &fc_11_fc_params,
        &fc_11_quant_params,
        &fc_11_input_dims,
        input,
        &fc_11_filter_dims,
        fc_11_weights,
        &fc_11_bias_dims,
        fc_11_bias,
        &fc_11_output_dims,
        output
    );

#endif // IS_PER_CHANNEL_QUANTIZATION

}
